### ISSUE TITLE
Turning off light when requesting "turn on"

### ISSUE THREAD

**Issue by neo2k1ca** [damianxd/homebridge-vera#104]
Just grabbed the newest build installing it via

sudo npm install -g homebridge-vera

I've been reading some of the past issues and I thought the fixes have been implemented and can be installed using the command above. If not, is there a command I can enter that'll help me resolve the "on=off" issue?

Thanks

**Comment by bitmerchandise** [comment]
Try this

sudo npm install -g --unsafe-perm damianxd/homebridge-vera

**Comment by neo2k1ca** [comment]
Thanks bit. I tried that, after uninstalling the previous one, but now don't have any communication whatsoever.

I also noticed in the log that homebridge loads but none of my accessories responds. In the homebridge.err file that as the various devices are loaded, I get this message and nothing else gets loaded:

Unhandled rejection Error: Accessories must be created with a valid UUID.
    at new Accessory (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:47:20)
    at Object.module.newDevice (/usr/lib/node_modules/homebridge-vera/lib/types/lock.js:58:25)
    at /usr/lib/node_modules/homebridge-vera/lib/functions.js:229:49
    at Array.forEach (native)
    at Object.module.processdevices (/usr/lib/node_modules/homebridge-vera/lib/functions.js:169:16)
    at Object.module.processall (/usr/lib/node_modules/homebridge-vera/lib/functions.js:78:32)
    at /usr/lib/node_modules/homebridge-vera/index.js:57:42
    at tryCatcher (/usr/lib/node_modules/homebridge-vera/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/homebridge-vera/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/lib/node_modules/homebridge-vera/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/lib/node_modules/homebridge-vera/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/lib/node_modules/homebridge-vera/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/usr/lib/node_modules/homebridge-vera/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/usr/lib/node_modules/homebridge-vera/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/usr/lib/node_modules/homebridge-vera/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
Mon, 06 Mar 2017 13:53:50 GMT VeraLink Caching status...

Veralink caching status repeats after.

**Comment by neo2k1ca** [comment]
From the homebridge.log file, I never get a confirmation that homebridge is running or that any of the vera devices have been processed. When I switch back to the other build (sudo npm install -g homebridge-vera) everything's back, including the original probs.

**Comment by drewcovi** [comment]
@neo2k1ca can you install from the GitHub URL? I'd avoid installing from NPM until we can get another publish.

**Comment by neo2k1ca** [comment]
Could i please get the proper syntax to install it taht way? I thought I tried that while tshooting yesterday but i may have done it wrong. thx

**Comment by bitmerchandise** [comment]
I had the same issues that you describe, when installing with the command I gave you

sudo npm install -g --unsafe-perm damianxd/homebridge-vera

Start with a fresh config.json, that is what resolved my issues. For some reason my old one was causing problems

**Comment by neo2k1ca** [comment]
thanks again, bit. I was just about to do that but thought i'd be rebuilding the config.json file exactly the same. I did findout how to install it via git though and now things are working.

git clone https://github.com/damianxd/homebridge-vera.git
cd homebridge-vera
git checkout dev
npm install -g ./

You can then remove the 'homebridge-vera' directory that was created by the 'git clone' command.

**Comment by drewcovi** [comment]
@neo2k1ca @bitmerchandise I just updated master with a better check for the garageLocks key, this should (hopefully) resolve your issues.  I assume garageLocks was not present in your config.json (which is totally expected, as its an optional parameter, so apologies on my end).

**Comment by neo2k1ca** [comment]
Right, I don't use that parameter but still updated everything. I'm assuming I'm pulling from the master using the commands above (i changed the one line also.)
