### ISSUE TITLE
Socket Hangup

### ISSUE THREAD

**Issue by reallybman** [damianxd/homebridge-vera#105]
Any idea what this means? It happens occasionally, but doesn't seem to cause a crash:

Unhandled rejection RequestError: Error: socket hang up
    at new RequestError (/usr/lib/node_modules/homebridge-vera/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/usr/lib/node_modules/homebridge-vera/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/usr/lib/node_modules/homebridge-vera/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/usr/lib/node_modules/homebridge-vera/node_modules/request/request.js:187:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at Request.onRequestError (/usr/lib/node_modules/homebridge-vera/node_modules/request/request.js:859:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at Socket.socketOnEnd (_http_client.js:394:9)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by damianxd** [comment]
It seems whenever you are running the homebridge app it's having troubles to connect to vera from time to time. Maybe a connection issue or Vera running slow and not attending the requests. You could try to check if Vera is running cpu intensive extensions, like Ergy. Or check your router for problems with the connection between devices. You could use the linux _ping_ command to keep requesting Vera and check if it does loose connection.

**Comment by drewcovi** [comment]
Oh yeah. Ergy is the worst. Always make sure that thing is nuked.

**Comment by drewcovi** [comment]
@reallybman for all intents and purposes this situation appears to be an outlier. If it works fora period of time then crashes there's likely an issue with your Vera. But right now no signs point to anything wrong with this plugin that would lead to the issues you've outlined.
