### ISSUE TITLE
Daily Crashing

### ISSUE THREAD

**Issue by erpeters3** [damianxd/homebridge-vera#109]
Here is the error I receive almost daily and have to restart Homebridge.

Unhandled rejection RequestError: Error: connect ENETDOWN 10.0.1.223:3480 - Local (10.0.1.13:59736)
at new RequestError (/usr/local/lib/node_modules/homebridge-vera/node_modules/request-promise-core/lib/errors.js:14:15)
at Request.plumbing.callback (/usr/local/lib/node_modules/homebridge-vera/node_modules/request-promise-core/lib/plumbing.js:87:29)
at Request.RP$callback [as _callback] (/usr/local/lib/node_modules/homebridge-vera/node_modules/request-promise-core/lib/plumbing.js:46:31)
at self.callback (/usr/local/lib/node_modules/homebridge-vera/node_modules/request/request.js:186:22)
at emitOne (events.js:96:13)
at Request.emit (events.js:188:7)
at Request.onRequestError (/usr/local/lib/node_modules/homebridge-vera/node_modules/request/request.js:845:8)
at emitOne (events.js:96:13)
at ClientRequest.emit (events.js:188:7)
at Socket.socketErrorListener (_http_client.js:310:9)
at emitOne (events.js:96:13)
at Socket.emit (events.js:188:7)
at emitErrorNT (net.js:1276:8)
at _combinedTickCallback (internal/process/next_tick.js:74:11)
at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by drewcovi** [comment]
Can you verify that you have the correct IP address in your config, and that you can successfully ping that IP from wherever you're running homebridge? This is not an issue with the plugin... the first line includes ENETDOWN

**Comment by erpeters3** [comment]
Yes it is correct. Once restarted, HomeBridge and Vera plugin work perfectly for up to 36 hours. Then whe they stop I go and check Terminal to find this error, over and over and over. Restart, works perfectly again for about a day.

**Comment by drewcovi** [comment]
Which Vera do you have? Could be the refresh rate is overwhelming your unit...

**Comment by erpeters3** [comment]
Vera Plus with latest firmware. Running HomeBridge on latest MacOS.

**Comment by drewcovi** [comment]
Weird, and assuming you're running on a mac mini or something not set to sleep... can't say, but it certainly doesnt seem like it's in the plugin.  It's originating from request-promise-core so I'd check it out there.

I'll definitely re-open if we can get more info on this, but considering You've gotten it to work for 3 days before failure, it really seems to be more related to your system, and/or node environment. Perhaps checking for the latest version of node etc could help, since MacOS gets pretty regular updates.
