### ISSUE TITLE
Error at load

### ISSUE THREAD

**Issue by Valmorefr** [damianxd/homebridge-vera#114]
Juste updated home bridge-vera. Now I have the following error :
"Unhandled rejection TypeError: Cannot read property 'name' of undefined"

And the plugin stops loading...

Any idea on how to solve?

**Comment by drewcovi** [comment]
@valmorefr did you update from Master using the GitHub URL? Or from npm?

**Comment by Valmorefr** [comment]
I used 
sudo npm -g install homebridge-vera

**Comment by drewcovi** [comment]
Yep. I'm working with the founder of the plugin to get NPM publishing rights. Your install is way behind. Install using the URL for the GitHub repository.

**Comment by Valmorefr** [comment]
Thanks for the help. How do I change the address for install source?

**Comment by Valmorefr** [comment]
Thank you. I ran the update from github (says I have 0.6.2 now). Still have trouble loading the plugin (it hangs). I get this error : 

```
Unhandled rejection TypeError: Cannot read property 'name' of undefined
    at /usr/local/lib/node_modules/homebridge-vera/lib/types/sensor.js:131:45
    at /usr/local/lib/node_modules/homebridge-vera/lib/functions.js:246:45
    at Array.forEach (native)
    at Object.module.processdevices (/usr/local/lib/node_modules/homebridge-vera/lib/functions.js:208:16)
    at Object.module.processall (/usr/local/lib/node_modules/homebridge-vera/lib/functions.js:118:32)
    at functions.getVeraInfo.then (/usr/local/lib/node_modules/homebridge-vera/index.js:29:44)
    at tryCatcher (/usr/local/lib/node_modules/homebridge-vera/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-vera/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-vera/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/homebridge-vera/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-vera/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/usr/local/lib/node_modules/homebridge-vera/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/usr/local/lib/node_modules/homebridge-vera/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/usr/local/lib/node_modules/homebridge-vera/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)

```

**Comment by neptunix** [comment]
Looks like your device has an unsupported type (category + subcategory) IDs for Sensors.
Although it shouldn't crash.

If you'd like to debug, could you please edit `/usr/local/lib/node_modules/homebridge-vera/lib/types/sensor.js` file manually and add a line 
```
console.log("Device debug: " + JSON.stringify(device))
```
just after line 125:
```
    return function (device) {
```
and then rerun homebridge and post data from the log file (line stating with `Device debug: ...`)

**Comment by drewcovi** [comment]
Yes. We are seeing some issues with Generic Sensor type. So if the sensor is type 12 double check that it doesn't need to be configured. Should be right in Vera.

If the device is a Aeotec 6 in 1 then it almost definitely is this. We have another issue logged that deals with this. We unfortunately can't map those sensors to anything in HomeKit but as @neptunix mentions we certainly shouldn't be crashing.

**Comment by Valmorefr** [comment]
Thanks for the help. I am not sur this is the cause of the problem, as you pointed.
Now the homebridge-vera starts (Initializing Vera pltaform...)
I used to then have in the homebridge output log : 
```
Process Device N1 : name1
Process Device N2 : name2
...
```
Then  I would have : 
```
Initializing platform accessory 'name1'...
Initializing platform accessory 'name2'...
```

But now, suddenly, I don't have these anymore...
Anyway I can have a more verbose log so thaht I could figure out why no device is being processes???

Thanks you.

**Comment by drewcovi** [comment]
@valmorefr can you confirm what type of sensor you have?

**Comment by Valmorefr** [comment]
Sure (here are all the devices I have registered) :

- Fibaro smoke sensor (smoke + temp) x2
- Fibaro 3 in 1 sensor (movement + temp+ light)
- Fibaro flood sensor (water + temp)
- Fibaro door-lock sensor
- Alt UI

**Comment by cschaake** [comment]
Hello,

I've got the same issue as above after upgrading to homebridge-vera. Installed from npm. (don't know how to install from git).
Homebridge seems to load correctly (homebridge-vera and deactivated homebrigde-heyu plugins, nothing else).
But when I use the homekit app the following message is displayed in de error log:
Sat, 22 Apr 2017 11:53:05 GMT VeraLink TypeError: Cannot read property 'status' of undefined
    at Object.module.getVariable (/usr/lib/node_modules/homebridge-vera/lib/functions.js:29:22)
    at Object.getStatus (/usr/lib/node_modules/homebridge-vera/lib/types/light.js:49:45)
    at .<anonymous> (/usr/lib/node_modules/homebridge-vera/lib/types/light.js:89:41)
    at emitThree (events.js:116:13)
    at emit (events.js:194:7)
    at Characteristic.getValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:129:10)
    at Bridge.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:650:20)
    at Array.forEach (native)
    at Bridge.Accessory._handleGetCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:614:8)
    at emitMany (events.js:127:13)
    at HAPServer.emit (events.js:201:7)
    at HAPServer._handleCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:926:10)
    at HAPServer.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

Homekit is not getting any response of any device. When I turn the vera plugin off and use only the heyu plugin, homekit works fine.
I have a lot of devices connected to my Vera Edge, disabled most of them in de config of homebridge-vera.
Running on Raspberry PI (4.4.50-v7+ #970 SMP Mon Feb 20 19:18:29 GMT 2017 armv7l GNU/Linux)
Everything is updated to latest images.
Included the full error log.
[homebridge.zip](https://github.com/damianxd/homebridge-vera/files/948947/homebridge.zip)

**Comment by prbreezy** [comment]
Hi,

I'm getting the same error I clean some of my device that I used to have. I follow modifier the sensor page and bellow my debug trace:

> Device debug: {"id":139,"id_parent":1,"embedded":0,"disabled":0,"impl_file":"","altid":"11","ip":"","mac":"","time_created":"1480158488","states":[{"service":"urn:micasaverde-com:serviceId:ZWaveDevice1","variable":"Capabilities","value":"83,156,0,4,161,2,R,B,RS,|48:1,96:3,112,114,128,132:1,133,134,142,156,","id":0},{"service":"urn:micasaverde-com:serviceId:ZWaveDevice1","variable":"ManufacturerInfo","value":"271,2816,4097","id":1},{"service":"urn:micasaverde-com:serviceId:ZWaveDevice1","variable":"VersionInfo","value":"3,3,67,25,25","id":2},{"service":"urn:micasaverde-com:serviceId:ZWaveDevice1","variable":"VariablesSet","value":"1-Alarm cancellation delay seconds (0-3600),2d,,2-Accoustic and visual signals,1d,,5-Type of alarm frame (flood),1d,0,7-Forced dimming,1d,,9-Alarm cancelling,1d,,10-Temperature measurement interval,2d,,12-Temperature measurement,2d,,13-Alarm broadcast,1d,,50-Low temperature alarm threshold,2d,,51-High temperature alarm threshold,2d,,61-Low temperature color,4d,,62-High temperature color,4d,,63-Managing LED operation,1d,,73-Temperature measurement compensation,2d,,74-Tamper alarms,1d,,75-Visual and audible alarm duartion,2d,,76-Retransmission time,2d,,77-Floor functionality bypass,1d,,","pnp":"*1.7.2607*","id":3},{"service":"urn:micasaverde-com:serviceId:HaDevice1","variable":"Documentation","value":"http://wiki.micasaverde.com/index.php/Fibaro_Flood_Sensor_FGFS-101","pnp":"*1.7.2607*","id":4},{"service":"urn:micasaverde-com:serviceId:ZWaveDevice1","variable":"Documentation","value":"http://wiki.micasaverde.com/index.php/Fibaro_Flood_Sensor_FGFS-101","pnp":"*1.7.2607*","id":5},{"service":"urn:micasaverde-com:serviceId:HaDevice1","variable":"Configured","value":"1","id":6},{"service":"urn:micasaverde-com:serviceId:ZWaveDevice1","variable":"NodeInfo","value":"30,60,70,72,80,84,85,86,8e,9c,","id":7},{"service":"urn:micasaverde-com:serviceId:ZWaveDevice1","variable":"MultiChEndpoint","value":"2,0,0","id":8},{"service":"urn:micasaverde-com:serviceId:ZWaveDevice1","variable":"MultiChCapabilities","value":"1,32,1,48,\n2,33,1,49,\n","id":9},{"service":"urn:micasaverde-com:serviceId:ZWaveDevice1","variable":"ConfiguredAssoc","value":"","id":10},{"service":"urn:micasaverde-com:serviceId:ZWaveDevice1","variable":"VariablesGet","value":"1,0,2,3,5,0,7,255,9,1,10,300,12,50,13,0,50,1500,51,3500,61,255,62,16711680,63,2,73,0,74,2,75,0,76,0,77,0,","id":11},{"service":"urn:micasaverde-com:serviceId:ZWaveDevice1","variable":"ConfiguredVariable","value":"1-Alarm cancellation delay seconds (0-3600),2d,,2-Accoustic and visual signals,1d,,5-Type of alarm frame (flood),1d,0,7-Forced dimming,1d,,9-Alarm cancelling,1d,,10-Temperature measurement interval,2d,,12-Temperature measurement,2d,,13-Alarm broadcast,1d,,50-Low temperature alarm threshold,2d,,51-High temperature alarm threshold,2d,,61-Low temperature color,4d,,62-High temperature color,4d,,63-Managing LED operation,1d,,73-Temperature measurement compensation,2d,,74-Tamper alarms,1d,,75-Visual and audible alarm duartion,2d,,76-Retransmission time,2d,,77-Floor functionality bypass,1d,,","id":12},{"service":"urn:micasaverde-com:serviceId:SecuritySensor1","variable":"Armed","value":"1","id":13},{"service":"urn:micasaverde-com:serviceId:HaDevice1","variable":"ModeSetting","value":"1:A;2:A;3:A;4:A","id":14},{"service":"urn:micasaverde-com:serviceId:HaDevice1","variable":"LastUpdate","value":"1480158500","id":15},{"service":"urn:micasaverde-com:serviceId:HaDevice1","variable":"FirstConfigured","value":"1480158500","id":16},{"service":"urn:micasaverde-com:serviceId:ZWaveDevice1","variable":"Neighbors","value":"1,","id":17},{"service":"urn:micasaverde-com:serviceId:ZWaveDevice1","variable":"LastReset","value":"1480158495","id":18},{"service":"urn:micasaverde-com:serviceId:ZWaveDevice1","variable":"AssociationNum","value":"3","id":19},{"service":"urn:micasaverde-com:serviceId:HaDevice1","variable":"BatteryDate","id":20,"value":"1494781796"},{"service":"urn:micasaverde-com:serviceId:HaDevice1","variable":"BatteryLevel","value":"78","id":21},{"service":"urn:micasaverde-com:serviceId:ZWaveDevice1","variable":"PollOk","id":22,"value":"1039"},{"service":"urn:micasaverde-com:serviceId:HaDevice1","variable":"PollRatings","value":"4.70","id":23},{"service":"urn:micasaverde-com:serviceId:ZWaveNetwork1","variable":"LastPollSuccess","id":24,"value":"1494781796"},{"service":"urn:micasaverde-com:serviceId:ZWaveNetwork1","variable":"ConsecutivePollFails","value":"0","id":25},{"service":"urn:micasaverde-com:serviceId:HaDevice1","variable":"sl_TamperAlarm","value":"0","id":26},{"service":"urn:micasaverde-com:serviceId:SecuritySensor1","variable":"LastTamper","value":"1480163305","id":27},{"service":"urn:micasaverde-com:serviceId:ZWaveDevice1","variable":"WakeupInterval","value":"1800","id":28},{"service":"urn:micasaverde-com:serviceId:HaDevice1","variable":"ChildrenSameRoom","value":"1","id":29},{"service":"urn:micasaverde-com:serviceId:ZWaveDevice1","variable":"LastWakeup","id":30,"value":"1494781795"},{"service":"urn:micasaverde-com:serviceId:ZWaveDevice1","variable":"LastNnu","value":"1494771033,145","id":31},{"service":"urn:micasaverde-com:serviceId:HaDevice1","variable":"WakeupRatings","value":"4.90","id":32},{"service":"urn:micasaverde-com:serviceId:ZWaveDevice1","variable":"LastArr","value":"1494769239,144","id":33},{"service":"urn:micasaverde-com:serviceId:ZWaveDevice1","variable":"LastRouteUpdate","value":"1494765653","id":34},{"service":"urn:micasaverde-com:serviceId:ZWaveDevice1","variable":"PollNoReply","value":"136","id":35},{"service":"urn:micasaverde-com:serviceId:SecuritySensor1","variable":"ArmedTripped","value":"0","id":36},{"service":"urn:upnp-org:serviceId:SwitchPower1","variable":"Status","value":"0","id":37},{"service":"urn:micasaverde-com:serviceId:HaDevice1","variable":"CommFailure","value":"0","id":38},{"service":"urn:micasaverde-com:serviceId:HaDevice1","variable":"CommFailureTime","value":"0","id":39},{"service":"urn:micasaverde-com:serviceId:HaDevice1","variable":"CommFailureAlarm","value":"1489743217,0","id":40},{"service":"urn:micasaverde-com:serviceId:SecuritySensor1","variable":"IgnoreTripTime","value":"2","id":41}],"pnp":"2227","manufacturer":"Fibaro","model":"FGFS-101","device_file":"D_FloodSensor1.xml","device_json":"D_FloodSensorWithTamper1.json","poll":["1494270442-1","1494281202-1","1494291959-1","1494302718-1","1494313476-1","1494324236-1","1494334985-1","1494345758-0","1494356491-1","1494367249-1","1494376218-1","1494399533-1","1494410306-1","1494421076-1","1494431844-1","1494442615-1","1494453384-1","1494464157-1","1494474929-1","1494485698-1","1494496466-1","1494500054-1","1494510823-1","1494521608-0","1494532353-1","1494543118-1","1494553889-1","1494564666-1","1494573647-1","1494582625-1","1494596986-1","1494607762-1","1494618533-1","1494629303-1","1494640069-1","1494650833-1","1494661604-1","1494668782-1","1494679545-1","1494692123-0","1494702870-1","1494713637-1","1494724408-1","1494735166-1","1494738756-1","1494749513-1","1494754892-1","1494765653-1","1494772830-1","1494781796-1"],"room":3,"ControlURLs":{"service_14":{"service":"urn:micasaverde-com:serviceId:SecuritySensor1","ControlURL":"/upnp/control/dev_14","EventURL":"/upnp/event/dev_14","serviceType":"urn:schemas-micasaverde-com:service:SecuritySensor:1"},"service_15":{"service":"urn:micasaverde-com:serviceId:HaDevice1","ControlURL":"/upnp/control/dev_15","EventURL":"/upnp/event/dev_15","serviceType":"urn:schemas-micasaverde-com:service:HaDevice:1"}},"device_type":"urn:schemas-micasaverde-com:device:FloodSensor:1","wakeup":{"list":[1494692100,1494693895,1494695689,1494697483,1494699279,1494701073,1494702867,1494704660,1494706455,1494708251,1494710045,1494711841,1494713634,1494715429,1494717223,1494719017,1494720812,1494722607,1494724401,1494726195,1494727987,1494729781,1494731574,1494733367,1494735161,1494738751,1494740545,1494742339,1494744133,1494745926,1494747720,1494749513,1494751306,1494753099,1494754892,1494756686,1494758480,1494760273,1494762066,1494763859,1494765652,1494767446,1494769239,1494771033,1494772827,1494774620,1494776414,1494778208,1494780001,1494781795],"lastKnown":1494688513},"name":"FS WasherDryer","local_udn":"uuid:4d494342-5342-5645-008b-000002b04a6d","category":4,"subcategory":2,"parent":1,"armed":"1","armedtripped":"0","batterylevel":"78","commFailure":"0","status":"0"}
Unhandled rejection TypeError: Cannot read property 'name' of undefined
    at C:\Users\prbreezy\AppData\Roaming\npm\node_modules\homebridge-vera\lib\types\sensor.js:132:45
    at C:\Users\prbreezy\AppData\Roaming\npm\node_modules\homebridge-vera\lib\functions.js:260:46
    at Array.forEach (native)
    at Object.module.checkCharacteristics.module.getVeraInfo.HAPnode.request.then.module.processdevices (C:\Users\prbreezy\AppData\Roaming\npm\node_modules\homebridge-vera\lib\functions.js:208:16)
    at Object.module.checkCharacteristics.module.getVeraInfo.HAPnode.request.then.module.processall (C:\Users\prbreezy\AppData\Roaming\npm\node_modules\homebridge-vera\lib\functions.js:118:32)
    at C:\Users\prbreezy\AppData\Roaming\npm\node_modules\homebridge-vera\index.js:29:44
    at tryCatcher (C:\Users\prbreezy\AppData\Roaming\npm\node_modules\homebridge-vera\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\prbreezy\AppData\Roaming\npm\node_modules\homebridge-vera\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\prbreezy\AppData\Roaming\npm\node_modules\homebridge-vera\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\prbreezy\AppData\Roaming\npm\node_modules\homebridge-vera\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\prbreezy\AppData\Roaming\npm\node_modules\homebridge-vera\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Users\prbreezy\AppData\Roaming\npm\node_modules\homebridge-vera\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\prbreezy\AppData\Roaming\npm\node_modules\homebridge-vera\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\prbreezy\AppData\Roaming\npm\node_modules\homebridge-vera\node_modules\bluebird\js\release\async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

Can someone else me please thanks !

**Comment by drewcovi** [comment]
@prbreezy I'll pick up a leak sensor in the next week so I can add this to the sensor list. I don't yet have one of these, so I can't develop blind.

For now I've updated the latests to not have a catastrophic failure on unrecognized subtypes.

Can you give it a spin and tell me if you're in the clear for now?

**Comment by Valmorefr** [comment]
Hi!

Just installed the update. Seems much better : it does process all devices like before. However it doesn't finish loading (I don't get to the homebridge HomeKit CODE display). 

I'll try tinkering with my confit tonight.

Cheers.

**Comment by prbreezy** [comment]
@drewcovi thanks for following up !

I try with the new version now I faced this :
But I can still used my Homebridge without any issue before I wasnt able..

5/16/2017, 2:53:30 PM] [Vera Edge] Initializing Vera platform...
[5/16/2017, 2:53:30 PM] [Living Room Harmony Hub] Plugin - Configure Accessory: Living Room
[5/16/2017, 2:53:30 PM] [Living Room Harmony Hub] Finalizing Plugin Launch
[5/16/2017, 2:53:30 PM] [yeelight] DidFinishLaunching
[5/16/2017, 2:53:30 PM] [Living Room Harmony Hub] Updated reachability of undefi ned to false
[5/16/2017, 2:53:31 PM] [yeelight] cached accessory: 0x00000000031ab537
already in device list!
Process Device 41: Fan
Process Device 70: Balcony LED
Process Device 116: Harmony Control
Unhandled rejection TypeError: Cannot read property 'deviceid' of null
at C:\Users\prbreezy\AppData\Roaming\npm\node_modules\homebridge-vera\lib\fu nctions.js:142:58
at Array.forEach (native)
at Object.module.checkCharacteristics.module.getVeraInfo.HAPnode.request.the n.HAPnode.request.then.module.processall.verainfo [as processall] (C:\Users\prbr eezy\AppData\Roaming\npm\node_modules\homebridge-vera\lib\functions.js:140:27)
at C:\Users\prbreezy\AppData\Roaming\npm\node_modules\homebridge-vera\index. js:29:44
at tryCatcher (C:\Users\prbreezy\AppData\Roaming\npm\node_modules\homebridge -vera\node_modules\bluebird\js\release\util.js:16:23)
at Promise._settlePromiseFromHandler (C:\Users\prbreezy\AppData\Roaming\npm\ node_modules\homebridge-vera\node_modules\bluebird\js\release\promise.js:512:31)
at Promise._settlePromise (C:\Users\prbreezy\AppData\Roaming\npm\node_module s\homebridge-vera\node_modules\bluebird\js\release\promise.js:569:18)
at Promise._settlePromise0 (C:\Users\prbreezy\AppData\Roaming\npm\node_modul es\homebridge-vera\node_modules\bluebird\js\release\promise.js:614:10)
at Promise._settlePromises (C:\Users\prbreezy\AppData\Roaming\npm\node_modul es\homebridge-vera\node_modules\bluebird\js\release\promise.js:693:18)
at Async._drainQueue (C:\Users\prbreezy\AppData\Roaming\npm\node_modules\hom ebridge-vera\node_modules\bluebird\js\release\async.js:133:16)
at Async._drainQueues (C:\Users\prbreezy\AppData\Roaming\npm\node_modules\ho mebridge-vera\node_modules\bluebird\js\release\async.js:143:10)
at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\prbreezy\AppData\ Roaming\npm\node_modules\homebridge-vera\node_modules\bluebird\js\release\async. js:17:14)
at processImmediate [as _immediateCallback] (timers.js:383:17)
connect ok!
[5/16/2017, 2:53:31 PM] [yeelight] accesseory reachable
[5/16/2017, 2:53:31 PM] [yeelight] dev connected 0x00000000031ab537 true

**Comment by drewcovi** [comment]
@prbreezy added another update, please check with the latest. I should have a leak sensor by Thursday.

**Comment by prbreezy** [comment]
@drewcovi 
It's working but on my iOS app my device stay in "Updating" or "No reponse" I can get them only through the Control center (by swiping up from my iPhone. - Can do a screenshot if you want).

**Comment by drewcovi** [comment]
Yeah, please confirm version of the plugin and actually if you can enable the debugging flag on homebridge that would be a huge help. It spits out a lot more details on possible issues. 

If you're not getting any errors anymore that's a huge step forward. 

It's also slightly possible that your HomeKit database still thinks the water sensors are around. I've pulled them until I can properly implement them. So clearing your device cache may also help.

**Comment by prbreezy** [comment]
Sure, but I don't see the sensor.js anymore should In which file I should put it now ?

So from the screenshot now I've this: http://imgur.com/jj7aR8K  or http://imgur.com/fPrZEKv No reponse and my hue for instance are good.

From my control center I can control them no problem : http://imgur.com/yiazILM

And yes now I dont see any error anymore Great progress !!!!

**Comment by Valmorefr** [comment]
Hi there. Updated everything. Still no luck... Here is what I get :
```
[2017-5-16 23:05:14] Loaded plugin: homebridge-ifttt
[2017-5-16 23:05:14] Registering platform 'homebridge-ifttt.IFTTT'
[2017-5-16 23:05:14] ---
[2017-5-16 23:05:15] Loaded plugin: homebridge-vera
VeraLink initializing
[2017-5-16 23:05:15] Registering platform 'homebridge-veralink.Vera'
[2017-5-16 23:05:15] ---
[2017-5-16 23:05:15] Loaded plugin: homebridge-yamaha
[2017-5-16 23:05:15] Registering accessory 'homebridge-yamaha.YamahaAVR'
[2017-5-16 23:05:15] Registering platform 'homebridge-yamaha.YamahaAVR'
[2017-5-16 23:05:15] ---
[2017-5-16 23:05:15] Loaded config.json with 0 accessories and 3 platforms.
[2017-5-16 23:05:15] ---
[2017-5-16 23:05:15] Loading 3 platforms...
[2017-5-16 23:05:15] [Homelive] Initializing Vera platform...
[2017-5-16 23:05:15] [Smappee] Initializing IFTTT platform...
[2017-5-16 23:05:15] [Smappee] Loading accessories...
[2017-5-16 23:05:15] [Smappee] Found: Loewe
[2017-5-16 23:05:15] [Smappee] Loading service: Loewe, subtype: veilles_salons_onveilles_salons_off
[2017-5-16 23:05:15] [Smappee] Initializing platform accessory 'Loewe'...
[2017-5-16 23:05:15] Initializing YamahaAVR platform...
[2017-5-16 23:05:15] Getting Yamaha AVR devices.
ZWave 1
_contrôleur de scénarios 1
Capteur 3 en 1 (mouvement) undefined
Capteur 3 en 1 (température) undefined
Capteur 3 en 1 (lumière) undefined
ALTUI undefined
Détecteur de fuite d'eau undefined
Détecteur de fuite d'eau (enfant redondant ???) 1
Détecteur de fuite d'eau (température) undefined
Détecteur d'ouverture porte undefined
Détecteur de fumée normalisé - undefined
détecteur de fumée (température) undefined
Détecteur de fumée undefined
détecteur de fumée (température) 1 undefined
Process Device 20: Capteur 3 en 1 (mouvement)
Process Device 23: Capteur 3 en 1 (température)
Process Device 24: Capteur 3 en 1 (lumière)
Unhandled rejection TypeError: Cannot read property 'deviceid' of null
    at /usr/local/lib/node_modules/homebridge-vera/lib/functions.js:143:58
    at Array.forEach (native)
    at Object.module.processall (/usr/local/lib/node_modules/homebridge-vera/lib/functions.js:141:27)
    at functions.getVeraInfo.then (/usr/local/lib/node_modules/homebridge-vera/index.js:29:44)
    at tryCatcher (/usr/local/lib/node_modules/homebridge-vera/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-vera/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-vera/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/homebridge-vera/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-vera/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/usr/local/lib/node_modules/homebridge-vera/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/usr/local/lib/node_modules/homebridge-vera/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/usr/local/lib/node_modules/homebridge-vera/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

[2017-5-16 23:05:17] Found Yamaha RX-V479 - 00D87503, "Scandyna Micropod 5.1"
[2017-5-16 23:05:50] Waited 30 seconds, stopping discovery.
[2017-5-16 23:05:50] Discovery finished, found 1 Yamaha AVR devices.
[2017-5-16 23:05:50] Initializing platform accessory 'Scandyna Micropod 5.1'...
```

Anyhting I can do to help? Cheers.

**Comment by drewcovi** [comment]
@valmorefr which version are you on for homebridge-Vera?

**Comment by Valmorefr** [comment]
`homebridge-vera@0.7.2 (git+https://github.com/damianxd/homebridge-vera.git#fcc81e7bb4b3611b60d4f047ff37dd1280e23a32)`

**Comment by drewcovi** [comment]
@valmorefr darn. Apparently git pus --tags doesn't push to master. Please try again. 

You can also fee free to migrate back to npm install homebridge-vera since I now have publish access.

**Comment by Valmorefr** [comment]
Awesome! Updated to 0.7.6 and it all works! I'll let you know if everything is fine. Thank you very much!!!
