### ISSUE TITLE
Triggers showing up as switches that have "No response" 

### ISSUE THREAD

**Issue by djrobx** [damianxd/homebridge-vera#121]
Not really sure why this started, but now my Homebridge is showing some of Vera's scene triggers as scenes.  On the phone they show a homekit switches with no response errors.

These come from one of my door locks, for example:

  VeraLink ------ Scene Added: Pin 1 Entered ID:13 +1ms
  VeraLink ------ Scene Added: Pin 2 Entered ID:14 +2ms
  VeraLink ------ Scene Added: Pin 3 Entered ID:15 +1ms
  VeraLink ------ Scene Added: Pin 4 Entered ID:16 +2ms

[4/26/2017, 9:16:12 PM] [Vera] Initializing platform accessory 'Pin 1 Entered'...
[4/26/2017, 9:16:12 PM] [Vera] Initializing platform accessory 'Pin 2 Entered'...
[4/26/2017, 9:16:12 PM] [Vera] Initializing platform accessory 'Pin 3 Entered'...
[4/26/2017, 9:16:12 PM] [Vera] Initializing platform accessory 'Pin 4 Entered'...

But these are NOT in the blob of json data starting with:

RESPONSE IS: { full: 1,
  version: '*1.5.622*',
  model: 'SERCOMM NA401',
  zwave_heal: 1,
  temperature: 'F',

scenes: 
   [ { active: 1, name: 'Alarm Arm', id: 30, room: 3 },
     { active: 1, name: 'Alarm Disarm', id: 31, room: 3 },
     { active: 0, name: 'All Xmas Off', id: 20, room: 7 },
     { active: 0, name: 'Attic Fan 1hr', id: 33, room: 4 },
     { active: 0, name: 'Attic Fan 4hr', id: 34, room: 4 },
     { active: 0, name: 'Automatic Hallway Lights', id: 9, room: 2 },
     { active: 0, name: 'Automatic Patio', id: 10, room: 3 },
     { active: 0, name: 'Change spa light show', id: 17, room: 6 },
     { active: 0, name: 'Default Spa Light Show', id: 19, room: 6 },
     { active: 0, name: 'HousekeepingLights', id: 25, room: 1 },
     { active: 0, name: 'Lock Spa Color', id: 18, room: 6 },
     { active: 0, name: 'Outside Xmas On', id: 21, room: 7 },
     { active: 0, name: 'Spa Filter Timer', id: 11, room: 6 },
     { active: 1, name: 'Spa Stop', id: 23, room: 6 },
     { active: 0, name: 'Turn off verification', id: 24, room: 1 } ],

These are not scenes, they are the triggers that can be used to trigger scenes.  

The only thing I've done recently is delete some devices.  I removed my Ecobee thermostat from Vera, as once a week my Vera is choking on the load and falling off the network.   Ecobee has its own homekit interface, and this homebridge works well enough I no longer use Vera apps.  :)

I'm running homebridge-vera version 0.70.   I see Damian has committed some changes to 0.71 but they don't look like they would affect this.

**Comment by djrobx** [comment]
*Update* I removed Homebridge's "persist" folder.  That seems to have stopped the "No repsonse" errors.  The triggers are still there but at least they're not making a ruckus.

**Comment by drewcovi** [comment]
This is likely due to Vera's ghost scenes that never die. They show up in user_data but not in sdata. 

We're using user_data at boot to pull manufacturer info for a more complete HomeKit experience, then polling sdata for updates. 

Either a pull request to prune the diff between sdata and user_data or removing these ghost scenes using your Vera and URL parameters usually gets the job done. That method involves sending the action over URL and the scene ID you get from the user_data request.

**Comment by drewcovi** [comment]
@djrobx can you check with the latest? I'm filtering based on whether or not the "invisible" key is set. Without seeing your json for user_data it's hard for me to filter on anything else.

**Comment by prbreezy** [comment]
@drewcovi thanks for following up !

I try with the new version and still facing the issue : 

> 5/16/2017, 2:53:30 PM] [Vera Edge] Initializing Vera platform...
[5/16/2017, 2:53:30 PM] [Living Room Harmony Hub] Plugin - Configure Accessory:                                       Living Room
[5/16/2017, 2:53:30 PM] [Living Room Harmony Hub] Finalizing Plugin Launch
[5/16/2017, 2:53:30 PM] [yeelight] DidFinishLaunching
[5/16/2017, 2:53:30 PM] [Living Room Harmony Hub] Updated reachability of undefi                                      ned to false
[5/16/2017, 2:53:31 PM] [yeelight] cached accessory: 0x00000000031ab537
already in device list!
Process Device 41: Fan
Process Device 70: Balcony LED
Process Device 116: Harmony Control
Unhandled rejection TypeError: Cannot read property 'deviceid' of null
    at C:\Users\prbreezy\AppData\Roaming\npm\node_modules\homebridge-vera\lib\fu                                      nctions.js:142:58
    at Array.forEach (native)
    at Object.module.checkCharacteristics.module.getVeraInfo.HAPnode.request.the                                      n.HAPnode.request.then.module.processall.verainfo [as processall] (C:\Users\prbr                                      eezy\AppData\Roaming\npm\node_modules\homebridge-vera\lib\functions.js:140:27)
    at C:\Users\prbreezy\AppData\Roaming\npm\node_modules\homebridge-vera\index.                                      js:29:44
    at tryCatcher (C:\Users\prbreezy\AppData\Roaming\npm\node_modules\homebridge                                      -vera\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\prbreezy\AppData\Roaming\npm\                                      node_modules\homebridge-vera\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\prbreezy\AppData\Roaming\npm\node_module                                      s\homebridge-vera\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\prbreezy\AppData\Roaming\npm\node_modul                                      es\homebridge-vera\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\prbreezy\AppData\Roaming\npm\node_modul                                      es\homebridge-vera\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Users\prbreezy\AppData\Roaming\npm\node_modules\hom                                      ebridge-vera\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\prbreezy\AppData\Roaming\npm\node_modules\ho                                      mebridge-vera\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\prbreezy\AppData\                                      Roaming\npm\node_modules\homebridge-vera\node_modules\bluebird\js\release\async.                                      js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
connect ok!
[5/16/2017, 2:53:31 PM] [yeelight] accesseory reachable
[5/16/2017, 2:53:31 PM] [yeelight] dev connected 0x00000000031ab537 true

**Comment by djrobx** [comment]
Hi @drewcovi,

Thanks for trying, no change unfortunately.    I've attached my user_data.   The scenes and devices in sdata are correct though.  Couldn't we ignore anything that is not in sdata? 

[user_data.txt](https://github.com/damianxd/homebridge-vera/files/1008291/user_data.txt)

**Comment by drewcovi** [comment]
Yes, we could run a diff, at the moment I'm working to better understand the origin of these scenes. I'm pretty sure we can just prune any notification_only scenes too.

These may be vestiges of past UIs

**Comment by djrobx** [comment]
> I'm pretty sure we can just prune any notification_only scenes too.

That sounds sensible enough. :) 

> These may be vestiges of past UIs

Very possible.   I've had a Vera for a reallllly long time, migrated from Vera1 to Vera2, although I'm pretty sure I've re-paired that lock since being on UI5.

**Comment by drewcovi** [comment]
If this is holding you back, for the time being you can delete these scenes directly using Vera's query string approach. I'd recommend it in general to remove cruft.

**Comment by djrobx** [comment]
I'm happy to delete the cruft, how do I do that?

**Comment by drewcovi** [comment]
Here's an example, replace the IP address and the scene ID

http://ip_address:3480/data_request?id=scene&action=delete&scene=5

**Comment by drewcovi** [comment]
More details @ http://wiki.micasaverde.com/index.php/Luup_Requests

**Comment by djrobx** [comment]
Drew's cruft removal instruction worked, and haven't seen any recurrences in a really really long time, so closing.
