### ISSUE TITLE
Cannot read property 'humidity' of undefined

### ISSUE THREAD

**Issue by thomashw** [damianxd/homebridge-vera#128]
I'm getting this error when running homebridge with homebridge-vera. Any ideas?

`VeraLink Caching status... +867ms
  VeraLink TypeError: Cannot read property 'humidity' of undefined
  VeraLink     at Object.module.getVariable (/usr/lib/node_modules/homebridge-vera/lib/functions.js:29:22)
  VeraLink     at Timeout._onTimeout (/usr/lib/node_modules/homebridge-vera/lib/types/sensor.js:177:44)
  VeraLink     at ontimeout (timers.js:386:14)
  VeraLink     at tryOnTimeout (timers.js:250:5)
  VeraLink     at Timer.listOnTimeout (timers.js:214:5) +130ms
  VeraLink TypeError: Cannot read property 'humidity' of undefined
  VeraLink     at Object.module.getVariable (/usr/lib/node_modules/homebridge-vera/lib/functions.js:29:22)
  VeraLink     at Timeout._onTimeout (/usr/lib/node_modules/homebridge-vera/lib/types/sensor.js:177:44)
  VeraLink     at ontimeout (timers.js:386:14)
  VeraLink     at tryOnTimeout (timers.js:250:5)
  VeraLink     at Timer.listOnTimeout (timers.js:214:5)
  VeraLink     at listOnTimeoutNT (timers.js:276:26)
  VeraLink     at _combinedTickCallback (internal/process/next_tick.js:77:11)
  VeraLink     at Immediate._tickCallback (internal/process/next_tick.js:104:9)
  VeraLink     at runCallback (timers.js:672:20)
  VeraLink     at tryOnImmediate (timers.js:645:5)
  VeraLink     at processImmediate [as _immediateCallback] (timers.js:617:5) +1ms
  VeraLink Caching status... +874ms
  VeraLink Caching status... +1s
  VeraLink Caching status... +1s
`

**Comment by thomashw** [comment]
When this occurs I receive "Updating" and then "No response" for all devices. If I change "includesensor" to false then things seem to work but my humidity sensor info is obviously gone.
