### ISSUE TITLE
ECONNREFUSED

### ISSUE THREAD

**Issue by erpeters3** [damianxd/homebridge-vera#135]
Keep getting this error over and over again in my terminal window:

Unhandled rejection RequestError: Error: connect ECONNREFUSED 10.0.1.223:3480
    at new RequestError (/usr/local/lib/node_modules/homebridge-vera/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/usr/local/lib/node_modules/homebridge-vera/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/usr/local/lib/node_modules/homebridge-vera/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/usr/local/lib/node_modules/homebridge-vera/node_modules/request/request.js:188:22)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at Request.onRequestError (/usr/local/lib/node_modules/homebridge-vera/node_modules/request/request.js:884:8)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketErrorListener (_http_client.js:256:9)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at emitErrorNT (net.js:1255:8)
    at nextTickCallbackWith2Args (node.js:437:9)
    at process._tickCallback (node.js:351:17)

**Comment by drewcovi** [comment]
Is your Vera's IP address fixed and 223? This appears to be specific to your Vera not allowing the connection. Or a dynamic IP.

**Comment by erpeters3** [comment]
Static. .223. Never was an issue. Relatively  new.

**Comment by mszf** [comment]
Same problem for me but for Vera Edge and Pi3 with fixed IP

**Comment by drewcovi** [comment]
@damianxd: might be tied to the latest release.

**Comment by prbreezy** [comment]
Hi 
I get this issue sometimes and I think I'm not 100% sure but this is due to a "reload luup" happening on the vera and during that time the homebridge is unable to access or get update from the vera I guess.. Maybe we can increase the timeout and bypass this issue ?

**Comment by prbreezy** [comment]
You can easily fwd your log to a syslog server from your vera and see what happen with the vera when you faced the ECONNREFUSED.

**Comment by erpeters3** [comment]
This was dormant for a while but is back with a vengeance.  Happens hundreds of times a day. My Vera is always reachable at this static IP.  All devices and gombrisge components are updated to latest.  Still works but with occasional latency, previously not an issue.

**Comment by erpeters3** [comment]
...and Homebridge components...

**Comment by spacesuitdiver** [comment]
@prbreezy I agree this is happening when vera is "updating" or something, you can get it to do happen if you delete a device. This probably just needs a retry coded in but I'm so sick of Vera's app I'm going back to ST to see if I can just address the few homebridge issues with that plugin instead :(

**Comment by erpeters3** [comment]
So I eventually connected this to a wake from sleep issue on my Vera.  Ordered a new average Plus and all is resolved.

**Comment by erpeters3** [comment]
new Vera Plus.

**Comment by spacesuitdiver** [comment]
@erpeters3 I'm using a brand new Vera Plus and this is an issue, the devices are both connected to the same switch even. You can probably reproduce by unpairing a device and trying to access the home app.
