### ISSUE TITLE
Error: Cannot find module 'undefined/lib/Accessory.js'

### ISSUE THREAD

**Issue by kieranmjones** [damianxd/homebridge-vera#136]
I've been having really issues connecting to my Vera lately, I've even gone to the length of removing all trace of nodejs etc from my computer and also factory reset the Vera thinking maybe something in it's config was breaking everything but I'm still having issues. I thought perhaps some of the required packages were missing but I can't establish which ones as everything seems to be present but clearly something is missing.

I get the following output when doing the initial configuration:

`kieran@Photon:~$ node node_modules/homebridge-vera/VeraLink.js 
prompt: IP address for your Vera device:  10.10.2.107
prompt: Port for your Vera device (hit enter to use default):  (6200) 
prompt: Bridged mode (Set to false to use single server for each device instead of one for each room):  (true) 
Room list: 
1 - Ghost

prompt: List of rooms to ignore, comma separated (default is empty):  1
Command-line input received:
	VeraIP: 10.10.2.107
	happort: 6200
	bridged: true
	ignorerooms: 1
Configuration saved!
module.js:491
    throw err;
    ^

Error: Cannot find module 'undefined/lib/Accessory.js'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at /home/kieran/node_modules/homebridge-vera/VeraLink.js:180:31
    at /home/kieran/node_modules/async/lib/async.js:718:13
    at iterate (/home/kieran/node_modules/async/lib/async.js:262:13)
    at /home/kieran/node_modules/async/lib/async.js:274:29
    at /home/kieran/node_modules/async/lib/async.js:44:16
    at /home/kieran/node_modules/async/lib/async.js:723:17
    at /home/kieran/node_modules/async/lib/async.js:167:37
    at /home/kieran/node_modules/homebridge-vera/VeraLink.js:167:21
    at FSReqWrap.oncomplete (fs.js:135:15)`

**Comment by kieranmjones** [comment]
I have actually found the problem, it seems that for this to work you need to run the command actually in the directory. 

In my case changing director to ~/node_modules/homebridge-vera/ and then running the command "node VeraLink.js" worked without any errors.

I'll close this issue.
