### ISSUE TITLE
Unhandled rejection Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory

### ISSUE THREAD

**Issue by gungun974** [damianxd/homebridge-vera#137]
Hello I encountered a problem in launching homebridge
Homebridge starts normally, it detect a platforms in the file config.json
It lists all the devices
then it initalizes the accesory platform then crash it by giving error message:
```
Unhandled rejection Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 6a113be1-bd76-4bb5-b4a6-bdaba028aa1d
    at Bridge.Accessory.addBridgedAccessory (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:257:13)
    at Server.<anonymous> (/usr/lib/node_modules/homebridge/lib/server.js:367:24)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:16:19
    at functions.getVeraInfo.then (/usr/lib/node_modules/homebridge-vera/index.js:33:15)
    at tryCatcher (/usr/lib/node_modules/homebridge-vera/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/homebridge-vera/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/lib/node_modules/homebridge-vera/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/lib/node_modules/homebridge-vera/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/lib/node_modules/homebridge-vera/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/usr/lib/node_modules/homebridge-vera/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/usr/lib/node_modules/homebridge-vera/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/usr/lib/node_modules/homebridge-vera/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```
I use a raspberry pi 3 for this and I have followed the instalation instructions below:
```
sudo apt-get update

sudo apt-get install nodejs npm git-core libnss-mdns libavahi-compat-libdnssd-dev

sudo npm config set registry http://registry.npmjs.org/

sudo npm install -g node-gyp

npm install -g --unsafe-perm homebridge

npm install -g --unsafe-perm `homebridge-vera
```

And here is my JSON file

```
{	
	"bridge": {
		"name": "Homebridge",
		"pin": "987-65-432",
		"username": "4E:3C:48:AC:AA:F3"
	},
	"platforms": [
		{
			"platform": "Vera",
			"name": "Vera",
			"veraIP": "192.168.1.14",
            "includesensor": false,
            "ignorerooms": [20,21,22],
            "securitypoll": 2000,
            "includethermostat": false,
            "includeRGB": false,
            "ignoredevices":[24,25],
            "ignorescenes":[26,27],
            "houseModes": false
		}
	]
}
```
Thanks for any future reply

**Comment by Barney57** [comment]
I have the same problem. 
Juste remove the device from the vera.
The device listed in initialisation tab when the app crash.
You need to repeat the association with vera.
It work for me.
Fibaro FGS-221 is the device offending.
