### ISSUE TITLE
Ios 11 Unhandled rejection error

### ISSUE THREAD

**Issue by freddo99** [damianxd/homebridge-vera#140]
I have updated to iOS 11, and have reloaded my Raspberry Pi 3.
If I delete the config.json file, the system boots up fully (but of course does not do anything due to missing file)
If I use my old config.json file I get errors 👎 

Unhandled rejection Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 21390b92-226c-4da5-a8f1-e61f0e4c1f3b
    at Bridge.Accessory.addBridgedAccessory (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:257:13)
    at Server.<anonymous> (/usr/lib/node_modules/homebridge/lib/server.js:367:24)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:16:19
    at functions.getVeraInfo.then (/usr/lib/node_modules/homebridge-vera/index.js:33:15)
    at tryCatcher (/usr/lib/node_modules/homebridge-vera/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/homebridge-vera/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/lib/node_modules/homebridge-vera/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/lib/node_modules/homebridge-vera/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/lib/node_modules/homebridge-vera/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/usr/lib/node_modules/homebridge-vera/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/usr/lib/node_modules/homebridge-vera/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/usr/lib/node_modules/homebridge-vera/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

Has anyone seen this ?...or know how to fix it ?

Thanks

**Comment by damianxd** [comment]
Please go to homebridge's github page and ask for support on this. But for us, the latests version of homebridge works flawlessly with homekit-vera
