### ISSUE TITLE
connect ENETUNREACH

### ISSUE THREAD

**Issue by reallybman** [damianxd/homebridge-vera#160]
Not sure what is causing this error. Never seen it before. 

Unhandled rejection RequestError: Error: connect ENETUNREACH 192.168.1.21:3480 - Local (0.0.0.0:0)
    at new RequestError (/usr/local/lib/node_modules/homebridge-vera/node_modules/request-promise/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/usr/local/lib/node_modules/homebridge-vera/node_modules/request-promise/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/usr/local/lib/node_modules/homebridge-vera/node_modules/request-promise/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/usr/local/lib/node_modules/homebridge-vera/node_modules/request/request.js:186:22)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at Request.onRequestError (/usr/local/lib/node_modules/homebridge-vera/node_modules/request/request.js:878:8)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketErrorListener (_http_client.js:269:9)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at emitErrorNT (net.js:1272:8)
    at nextTickCallbackWith2Args (node.js:511:9)
    at process._tickCallback (node.js:425:17)

**Comment by prbreezy** [comment]
This error is because your Vera was unreachable on the port 3480.
--> **Vera listens on port 3480. Vera responds to UPnP actions the normal way, or by making simple HTTP requests.**

Either you tried to turn on/off something or homebridge tried get a sensor state.

I used to have this error with my Vera the only thing you can do is to reinstall your vera that might fix the issue and install a monitoring tool like Nagios something like that to confirm this behavior.
