### ISSUE TITLE
Homebridge-Vera edge

### ISSUE THREAD

**Issue by ka4ev** [damianxd/homebridge-vera#166]
Unhandled rejection Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: cda377bc-ef0a-4e41-ab9c-3ed9e42675e9
    at Bridge.Accessory.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:264:13)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:398:24)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:16:19
    at functions.getVeraInfo.then (/usr/local/lib/node_modules/homebridge-vera/index.js:33:15)
    at tryCatcher (/usr/local/lib/node_modules/homebridge-vera/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-vera/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-vera/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/homebridge-vera/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-vera/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/usr/local/lib/node_modules/homebridge-vera/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/usr/local/lib/node_modules/homebridge-vera/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/usr/local/lib/node_modules/homebridge-vera/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

What that means anyone have any idea? Homebridge is installed on Mac mini was working fine until a few days ago.

**Comment by anupchavda1** [comment]
same as this issue i think:

https://github.com/damianxd/homebridge-vera/issues/164

**Comment by ka4ev** [comment]
Can anybody try to resolve this issue ?

**Comment by drewcovi** [comment]
This is unfortunately not an issue with this plugin. Happens all the time to many folks. I’d advise trying the solutions here: https://github.com/nfarina/homebridge/issues/1695

If it’s possible to pin this down to homebridge-vera I’ll reopen

**Comment by ka4ev** [comment]
Thank you very much! I have tried to solve the issue as you suggest but this didn’t help issues still remains.
