### ISSUE TITLE
Unhandled rejection Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory:

### ISSUE THREAD

**Issue by fernmac2** [damianxd/homebridge-vera#168]
Hi, I could use some help with this error. I already deleted the persist and accessories folders and restarted with no success. Any help would be great.

Log:
[10/20/2018, 6:42:40 PM] [Vera] Initializing platform accessory 'Estores qd chego à noite'...
[10/20/2018, 6:42:40 PM] [Vera] Initializing platform accessory 'Porta'...
Unhandled rejection Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: d227b333-5eda-46e4-9c94-bae686a11767
    at Bridge.Accessory.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:264:13)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:399:24)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:16:19
    at functions.getVeraInfo.then (/usr/local/lib/node_modules/homebridge-vera/index.js:33:15)
    at tryCatcher (/usr/local/lib/node_modules/homebridge-vera/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-vera/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-vera/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/homebridge-vera/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-vera/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/usr/local/lib/node_modules/homebridge-vera/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/usr/local/lib/node_modules/homebridge-vera/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/usr/local/lib/node_modules/homebridge-vera/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/homebridge-vera/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)

**Comment by ka4ev** [comment]
I have the same problem!

**Comment by ceou** [comment]
i have the same problem

**Comment by ChrisHolcomb** [comment]
I have the same problem, has anyone figured out how to get around or fix this?

**Comment by ChrisHolcomb** [comment]
This works good for listing your devices and finding duplicates:
http://192.168.xxx.xxx:3480/data_request?id=invoke

Mine was a scene so I used: 
http://ip_address:3480/data_request?id=scene&action=delete&scene=5

Still not able to connect but at least the homebridge is starting up.

**Comment by ChrisHolcomb** [comment]
Finally got mine to work. I deleted the ~/.homebridge/persists folder, and changed my username. But I think the actually fix was updating node to v10+, it seems it is required but never complains about it.
