### ISSUE TITLE
Unhandled rejection RequestError: Error:

### ISSUE THREAD

**Issue by deboy69** [damianxd/homebridge-vera#176]
Getting a bunch of these errors. Any ideas? Thanks

Unhandled rejection RequestError: Error: connect ECONNREFUSED 192.168.1.227:3480
    at new RequestError (/usr/lib/node_modules/homebridge-vera/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/usr/lib/node_modules/homebridge-vera/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/usr/lib/node_modules/homebridge-vera/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/usr/lib/node_modules/homebridge-vera/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.onRequestError (/usr/lib/node_modules/homebridge-vera/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:198:13)
    at Socket.socketErrorListener (_http_client.js:392:9)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by damianxd** [comment]
Are you sure that's your vera IP address? what do you get when you browse on that address? http://192.168.1.227:3480

**Comment by deboy69** [comment]
I can confirm that it’s my IP address. However everything seems to be working just fine though given the error

**Comment by damianxd** [comment]
But is it the Vera’s IP address

On 17-06-2020, at 09:27, deboy69 <notifications@github.com> wrote:

﻿

I can confirm that it’s my IP address. However everything seems to be working just fine though given the error

**Comment by deboy69** [comment]
It is the vera IP address

**Comment by deboy69** [comment]
Any idea what is causing the errors?

**Comment by deboy69** [comment]
Bueller.... Bueller.. Bueller... LOL?

**Comment by deboy69** [comment]
Any help on this issue? Causes a bit of a delay when talking to siri

**Comment by drewcovi** [comment]
Unfortunately I believe we’re going to have to find new maintainers of homebridge-Vera or accept a pull request. I think Damian has moved on to Homey and I’ve decided to make the move to Hubitat. I can say this was working for me as recently as last month, with lightning fast response times and your issue seems to be isolated (many others use this plug-in). Happy to accept a pull request if you track down the solution.

**Comment by deboy69** [comment]
it works most of the time but when the error happens its slow sometimes up to 10-15 second delay. Ill see what I can come up with

**Comment by deboy69** [comment]
What Ive test and will report back. See if that will fix it. 
Opened terminal in homebridge and went to /homebridge/node_modules/homebridge-vera
Opened VeraLink.js
Changed /:3480 to /port_3480

**Comment by krehman** [comment]
@deboy69 / @drewcovi can we get a published beta version with the latest changes in the code? **0.8.3-beta.13**? How can I manually merge these changes with my homebridge instance? 

Thanks.
