### ISSUE TITLE
I can not find any of the Vera door sensors

### ISSUE THREAD

**Issue by miketartaglia** [damianxd/homebridge-vera#184]
Does this plugin allow for access to the vera's door sensors?  It would be great to be able to use Homekit Automations with those sensors.  I'm not able to see these sensors in Homebridge or Homekit, so I assume the plugin either isn't configured correctly or it doesn't support them.

**Comment by drewcovi** [comment]
It does

**Comment by miketartaglia** [comment]
Any help in finding these sensors would be appreciated.  I have been running this plug-in for sometime now.  What do you need from me to troubleshoot this?

**Comment by drewcovi** [comment]
@miketartaglia quick check to verify you have `includesensor: true` in your config?

**Comment by miketartaglia** [comment]
I do have the includesensor in the config, however, when I set it to true home bridge never restarts.  I can not find anything in the logs telling me why so I have always had it to false.  Plus the documentation said it is used for thermostat sensors, not door sensors.

**Comment by drewcovi** [comment]
yeah, the documentation is definitely antiquated. it was expanded to include all sensors. when you say it never restarts... I would be curious to hear why. I can say that for many years I used all sorts of contact sensors with that config variable set to true. do you have debugging turned on in homebridge? based on what you're using you should be able to do it either in the web ui, or within the command line.

**Comment by miketartaglia** [comment]
I have enabled debug mode, and put true in for includesensor.  Restarting now.

**Comment by miketartaglia** [comment]
I don't see anything new in the logs.  Maybe I am looking in the wrong spot.

**Comment by drewcovi** [comment]
is the entire homebridge hanging and not working?

**Comment by drewcovi** [comment]
it should be DEBUG=* as well as the -D flag.

**Comment by miketartaglia** [comment]
Yes the entire home bridge hangs and all my vera devices are not responding in homekit.

**Comment by miketartaglia** [comment]
Does it matter that I am running homebridge in a docker container?

**Comment by drewcovi** [comment]
can't say for sure. I know I did myself as well. but you should absolutely be seeing quite a bit of logging, so that's honestly where I would start (even with sensors turned off for now).

**Comment by miketartaglia** [comment]
I have an old vera 3, could that be the issue?

**Comment by drewcovi** [comment]
totally possible, although unlikely it would crash anything. I had a vera 3 for years, and moved to veraplus a few years back, but I'd still work to ensure you have debugging showing more information. if you can send some of those logs this way to ensure you're getting `homebridge-vera` debug level logs.

**Comment by miketartaglia** [comment]
I got the debug logs to work. Here is what is at the end of the logs (which keeps going and never stops).

Mon, 11 Jan 2021 18:52:24 GMT VeraLink Caching status...
Mon, 11 Jan 2021 18:52:24 GMT VeraLink Power state called: undefined true
Mon, 11 Jan 2021 18:52:25 GMT VeraLink Caching status...
Mon, 11 Jan 2021 18:52:26 GMT VeraLink Caching status...
Mon, 11 Jan 2021 18:52:27 GMT VeraLink Caching status...
Mon, 11 Jan 2021 18:52:28 GMT VeraLink Caching status...
Mon, 11 Jan 2021 18:52:29 GMT VeraLink Caching status...
Mon, 11 Jan 2021 18:52:30 GMT VeraLink Caching status...
Mon, 11 Jan 2021 18:52:31 GMT VeraLink Caching status...
Mon, 11 Jan 2021 18:52:32 GMT VeraLink Caching status...
Mon, 11 Jan 2021 18:52:33 GMT VeraLink Caching status...
Mon, 11 Jan 2021 18:52:34 GMT VeraLink Caching status...
Mon, 11 Jan 2021 18:52:35 GMT VeraLink Caching status...
Mon, 11 Jan 2021 18:52:36 GMT VeraLink Caching status...
Mon, 11 Jan 2021 18:52:37 GMT VeraLink Caching status...
Mon, 11 Jan 2021 18:52:38 GMT VeraLink Caching status...
Mon, 11 Jan 2021 18:52:39 GMT VeraLink Caching status...
Mon, 11 Jan 2021 18:52:40 GMT VeraLink Caching status...
Mon, 11 Jan 2021 18:52:41 GMT VeraLink Caching status...
Mon, 11 Jan 2021 18:52:42 GMT VeraLink Caching status...
Mon, 11 Jan 2021 18:52:43 GMT VeraLink Caching status...
Mon, 11 Jan 2021 18:52:44 GMT VeraLink Caching status...
Mon, 11 Jan 2021 18:52:45 GMT VeraLink Caching status...
Mon, 11 Jan 2021 18:52:46 GMT VeraLink Caching status...

**Comment by miketartaglia** [comment]
Normally it would only show about 7 lines of  'GMT VeraLink Caching status...'

**Comment by drewcovi** [comment]
I would recommend installing direct from the repository for now to ensure you have the latest. it doesn't appear that a new release has been cut for quite some time. so in your package.json `damianxd/homebridge-vera` 

that status log doesn't exist in the latest code...

**Comment by miketartaglia** [comment]
I will have to search to figure out how to do that.  thanks for your help.

**Comment by drewcovi** [comment]
if you're using docker, it should be a file in your persist directory. quick update should get you there, but still id say that the important logs are shown during initialization, not during caching.

I would also consider removing other plugins and just attempting this one at first to make sure its not some strange plugin conflict.

**Comment by miketartaglia** [comment]
just curious, what version of the plugin is the latest?

**Comment by drewcovi** [comment]
so you probably do have the latest NPM release and one thing you'll get from master is the removal of that logging during status polling. however that's not likely to be the issue, and the logging that will be the most useful will be those messages during initialization (so you'll need to scroll back and look for any errors).

**Comment by drewcovi** [comment]
master is bleeding edge, but we're long overdue for another cut.

**Comment by drewcovi** [comment]
this portion should absolutely be giving you messages along the lines of `---- Sensor added`

```js
case 4: // Security Sensors
                  case 16: // Humidity Sensor
                  case 18: // Light Sensor
                        if(config.includesensor)
                        {
                            var Sensor = require("./types/sensor.js")(HAPnode,config,module);
                            if(Sensor(device)){
                              accessories.push(Sensor(device));
                              HAPnode.debug('------ Sensor Added: %s', device.name + ' ID:' +device.id);
                            }
                        }
                      break;
```

**Comment by miketartaglia** [comment]
Oh I thought you wanted me to download the latest version of the plugin.  Now I'm a little confused LOL

**Comment by miketartaglia** [comment]
I have just updated the docker image I use for Homebridge which allowed me to update Node.js to the latest.  However, I still can not enable sensors in the config for homebridge and debug mode shows me nothing new.

**Comment by drewcovi** [comment]
Could you disable all other plugins and turn on sensors then send a log of the initialization? Should be right around where it gives you the HomeKit code

**Comment by miketartaglia** [comment]
The only way I know how to disable a plugin is to uninstall it.  I have two plugins that I do not want to lose the settings for.  Is it a matter of just removing the configuration setting sin the json file?  I could easily restore a backup later.

**Comment by drewcovi** [comment]
Settings in HomeKit? Or settings in config.json? Config.json you should be able to simply cut those lines and put them in another text file temporarily. But I believe there’s an easier way these days to whitelist certain plugins. https://github.com/homebridge/homebridge/pull/1880#issuecomment-394766881

**Comment by miketartaglia** [comment]
I was able to remove all plugins from the json file.  I then restarted to make sure it worked.   Then I put true in for sensors.  Restarted and it doesn't start.  I am attaching some of the log to here.

0B (UPS: 1440)
Tue, 12 Jan 2021 13:06:33 GMT VeraLink Caching status...
Tue, 12 Jan 2021 13:06:34 GMT VeraLink Caching status...
Tue, 12 Jan 2021 13:06:35 GMT VeraLink Caching status...
Tue, 12 Jan 2021 13:06:36 GMT VeraLink Caching status...
Tue, 12 Jan 2021 13:06:37 GMT VeraLink Caching status...
Tue, 12 Jan 2021 13:06:38 GMT VeraLink Caching status...
2021-01-12T13:06:39.698Z ciao:Responder Sending (delayed 75ms) response via multicast on network interface docker0 (took 1 ms): [PTR] answers and [TXT,SRV,A,AAAA,NSEC,NSEC] additionals with size 342B
2021-01-12T13:06:39.700Z ciao:Responder Sending (delayed 77ms) response via multicast on network interface eth0 (took 0 ms): [PTR] answers and [TXT,SRV,A,AAAA,AAAA,NSEC,NSEC] additionals with size 370B
2021-01-12T13:06:39.709Z HAP-NodeJS:EventedHTTPServer [::ffff:192.168.3.237] New connection from client at interface eth0
2021-01-12T13:06:39.709Z HAP-NodeJS:EventedHTTPServer [::ffff:192.168.3.237] HTTP server listening on port 44878
2021-01-12T13:06:39.716Z HAP-NodeJS:EventedHTTPServer [::ffff:192.168.3.237] HTTP request: /accessories
2021-01-12T13:06:39.716Z HAP-NodeJS:HAPServer [0E:BB:BE:8A:11:8B] HAP Request: GET /accessories
2021-01-12T13:06:39.757Z HAP-NodeJS:EventedHTTPServer [::ffff:192.168.3.237] HTTP Response is finished
2021-01-12T13:06:39.763Z HAP-NodeJS:EventedHTTPServer [::ffff:192.168.3.237] HTTP connection was closed
2021-01-12T13:06:39.764Z HAP-NodeJS:EventedHTTPServer [::ffff:192.168.3.237] HTTP server was closed
2021-01-12T13:06:39.764Z HAP-NodeJS:EventedHTTPServer [::ffff:192.168.3.237] Client connection closed
Tue, 12 Jan 2021 13:06:39 GMT VeraLink Caching status...
Tue, 12 Jan 2021 13:06:40 GMT VeraLink Caching status...
Tue, 12 Jan 2021 13:06:41 GMT VeraLink Caching status...
Tue, 12 Jan 2021 13:06:42 GMT VeraLink Caching status...
Tue, 12 Jan 2021 13:06:43 GMT VeraLink Caching status...
Tue, 12 Jan 2021 13:06:44 GMT VeraLink Caching status...
Tue, 12 Jan 2021 13:06:45 GMT VeraLink Caching status...
Tue, 12 Jan 2021 13:06:46 GMT VeraLink Caching status...
Tue, 12 Jan 2021 13:06:47 GMT VeraLink Caching status...
Tue, 12 Jan 2021 13:06:48 GMT VeraLink Caching status...
Tue, 12 Jan 2021 13:06:49 GMT VeraLink Caching status...
2021-01-12T13:06:50.273Z ciao:Responder Sending (delayed 69ms) response via multicast on network interface docker0 (took 1 ms): [PTR] answers and [TXT,SRV,A,AAAA,NSEC,NSEC] additionals with size 342B
2021-01-12T13:06:50.294Z ciao:Responder Sending (delayed 89ms) response via multicast on network interface eth0 (took 1 ms): [PTR] answers and [TXT,SRV,A,AAAA,AAAA,NSEC,NSEC] additionals with size 370B
2021-01-12T13:06:50.303Z HAP-NodeJS:EventedHTTPServer [::ffff:192.168.3.237] New connection from client at interface eth0
2021-01-12T13:06:50.303Z HAP-NodeJS:EventedHTTPServer [::ffff:192.168.3.237] HTTP server listening on port 45127
2021-01-12T13:06:50.307Z HAP-NodeJS:EventedHTTPServer [::ffff:192.168.3.237] HTTP request: /accessories
2021-01-12T13:06:50.307Z HAP-NodeJS:HAPServer [0E:BB:BE:8A:11:8B] HAP Request: GET /accessories
2021-01-12T13:06:50.342Z HAP-NodeJS:EventedHTTPServer [::ffff:192.168.3.237] HTTP Response is finished
2021-01-12T13:06:50.346Z HAP-NodeJS:EventedHTTPServer [::ffff:192.168.3.237] HTTP connection was closed
2021-01-12T13:06:50.347Z HAP-NodeJS:EventedHTTPServer [::ffff:192.168.3.237] HTTP server was closed
2021-01-12T13:06:50.347Z HAP-NodeJS:EventedHTTPServer [::ffff:192.168.3.237] Client connection closed
Tue, 12 Jan 2021 13:06:50 GMT VeraLink Caching status...
Tue, 12 Jan 2021 13:06:51 GMT VeraLink Caching status...
Tue, 12 Jan 2021 13:06:52 GMT VeraLink Caching status...
Tue, 12 Jan 2021 13:06:53 GMT VeraLink Caching status...
Tue, 12 Jan 2021 13:06:54 GMT VeraLink Caching status...
Tue, 12 Jan 2021 13:06:55 GMT VeraLink Caching status...
Tue, 12 Jan 2021 13:06:56 GMT VeraLink Caching status...
Tue, 12 Jan 2021 13:06:57 GMT VeraLink Caching status...
Tue, 12 Jan 2021 13:06:58 GMT VeraLink Caching status...
Tue, 12 Jan 2021 13:06:59 GMT VeraLink Caching status...
2021-01-12T13:07:00.649Z ciao:Responder Sending (delayed 40ms) response via multicast on network interface docker0 (took 1 ms): [PTR] answers and [TXT,SRV,A,AAAA,NSEC,NSEC] additionals with size 342B
2021-01-12T13:07:00.651Z ciao:Responder Sending (delayed 41ms) response via multicast on network interface eth0 (took 1 ms): [PTR] answers and [TXT,SRV,A,AAAA,AAAA,NSEC,NSEC] additionals with size 370B
2021-01-12T13:07:00.665Z HAP-NodeJS:EventedHTTPServer [::ffff:192.168.3.237] New connection from client at interface eth0
2021-01-12T13:07:00.666Z HAP-NodeJS:EventedHTTPServer [::ffff:192.168.3.237] HTTP server listening on port 45454
2021-01-12T13:07:00.671Z HAP-NodeJS:EventedHTTPServer [::ffff:192.168.3.237] HTTP request: /accessories
2021-01-12T13:07:00.671Z HAP-NodeJS:HAPServer [0E:BB:BE:8A:11:8B] HAP Request: GET /accessories
2021-01-12T13:07:00.710Z HAP-NodeJS:EventedHTTPServer [::ffff:192.168.3.237] HTTP Response is finished
2021-01-12T13:07:00.711Z HAP-NodeJS:EventedHTTPServer [::ffff:192.168.3.237] HTTP connection was closed
2021-01-12T13:07:00.711Z HAP-NodeJS:EventedHTTPServer [::ffff:192.168.3.237] HTTP server was closed
2021-01-12T13:07:00.712Z HAP-NodeJS:EventedHTTPServer [::ffff:192.168.3.237] Client connection closed
Tue, 12 Jan 2021 13:07:00 GMT VeraLink Caching status...
Tue, 12 Jan 2021 13:07:01 GMT VeraLink Caching status...
Tue, 12 Jan 2021 13:07:02 GMT VeraLink Caching status...
Tue, 12 Jan 2021 13:07:03 GMT VeraLink Caching status...
Tue, 12 Jan 2021 13:07:04 GMT VeraLink Caching status...
2021-01-12T13:07:04.924Z ciao:Responder Sending response via unicast to {"address":"192.168.3.14","port":5353,"interface":"docker0"} (took 1 ms): [PTR] answers and [TXT,SRV,A,AAAA,NSEC,NSEC] additionals with size 342B (UPS: 1440)
2021-01-12T13:07:04.927Z ciao:Responder Sending response via unicast to {"address":"192.168.3.14","port":5353,"interface":"eth0"} (took 1 ms): [PTR] answers and [TXT,SRV,A,AAAA,AAAA,NSEC,NSEC] additionals with size 370B (UPS: 1440)
Tue, 12 Jan 2021 13:07:05 GMT VeraLink Caching status...
Tue, 12 Jan 2021 13:07:06 GMT VeraLink Caching status...
Tue, 12 Jan 2021 13:07:07 GMT VeraLink Caching status...
Tue, 12 Jan 2021 13:07:08 GMT VeraLink Caching status...
Tue, 12 Jan 2021 13:07:09 GMT VeraLink Caching status...
Tue, 12 Jan 2021 13:07:10 GMT VeraLink Caching status...
2021-01-12T13:07:11.229Z ciao:Responder Sending (delayed 72ms) response via multicast on network interface eth0 (took 1 ms): [PTR] answers and [TXT,SRV,A,AAAA,AAAA,NSEC,NSEC] additionals with size 370B
2021-01-12T13:07:11.240Z HAP-NodeJS:EventedHTTPServer [::ffff:192.168.3.237] New connection from client at interface eth0
2021-01-12T13:07:11.240Z HAP-NodeJS:EventedHTTPServer [::ffff:192.168.3.237] HTTP server listening on port 36562
2021-01-12T13:07:11.241Z HAP-NodeJS:EventedHTTPServer [::ffff:192.168.3.237] HTTP request: /accessories
2021-01-12T13:07:11.242Z HAP-NodeJS:HAPServer [0E:BB:BE:8A:11:8B] HAP Request: GET /accessories
2021-01-12T13:07:11.263Z HAP-NodeJS:EventedHTTPServer [::ffff:192.168.3.237] HTTP Response is finished
2021-01-12T13:07:11.264Z ciao:Responder Sending (delayed 108ms) response via multicast on network interface docker0 (took 1 ms): [PTR] answers and [TXT,SRV,A,AAAA,NSEC,NSEC] additionals with size 342B
2021-01-12T13:07:11.270Z HAP-NodeJS:EventedHTTPServer [::ffff:192.168.3.237] HTTP connection was closed
2021-01-12T13:07:11.271Z HAP-NodeJS:EventedHTTPServer [::ffff:192.168.3.237] HTTP server was closed
2021-01-12T13:07:11.271Z HAP-NodeJS:EventedHTTPServer [::ffff:192.168.3.237] Client connection closed
Tue, 12 Jan 2021 13:07:11 GMT VeraLink Caching status...
Tue, 12 Jan 2021 13:07:12 GMT VeraLink Caching status...
Tue, 12 Jan 2021 13:07:13 GMT VeraLink Caching status...
Tue, 12 Jan 2021 13:07:14 GMT VeraLink Caching status...
Tue, 12 Jan 2021 13:07:15 GMT VeraLink Caching status...
Tue, 12 Jan 2021 13:07:16 GMT VeraLink Caching status...
Tue, 12 Jan 2021 13:07:17 GMT VeraLink Caching status...
Tue, 12 Jan 2021 13:07:18 GMT VeraLink Caching status...
Tue, 12 Jan 2021 13:07:19 GMT VeraLink Caching status...
Tue, 12 Jan 2021 13:07:20 GMT VeraLink Caching status...
2021-01-12T13:07:21.772Z ciao:Responder Sending (delayed 100ms) response via multicast on network interface docker0 (took 0 ms): [PTR] answers and [TXT,SRV,A,AAAA,NSEC,NSEC] additionals with size 342B
2021-01-12T13:07:21.792Z ciao:Responder Sending (delayed 119ms) response via multicast on network interface eth0 (took 0 ms): [PTR] answers and [TXT,SRV,A,AAAA,AAAA,NSEC,NSEC] additionals with size 370B
2021-01-12T13:07:21.800Z HAP-NodeJS:EventedHTTPServer [::ffff:192.168.3.237] New connection from client at interface eth0
2021-01-12T13:07:21.800Z HAP-NodeJS:EventedHTTPServer [::ffff:192.168.3.237] HTTP server listening on port 36622
2021-01-12T13:07:21.802Z HAP-NodeJS:EventedHTTPServer [::ffff:192.168.3.237] HTTP request: /accessories
2021-01-12T13:07:21.802Z HAP-NodeJS:HAPServer [0E:BB:BE:8A:11:8B] HAP Request: GET /accessories
2021-01-12T13:07:21.838Z HAP-NodeJS:EventedHTTPServer [::ffff:192.168.3.237] HTTP Response is finished
Tue, 12 Jan 2021 13:07:21 GMT VeraLink Caching status...
2021-01-12T13:07:21.841Z HAP-NodeJS:EventedHTTPServer [::ffff:192.168.3.237] HTTP connection was closed
2021-01-12T13:07:21.841Z HAP-NodeJS:EventedHTTPServer [::ffff:192.168.3.237] HTTP server was closed
2021-01-12T13:07:21.841Z HAP-NodeJS:EventedHTTPServer [::ffff:192.168.3.237] Client connection closed
Tue, 12 Jan 2021 13:07:22 GMT VeraLink Caching status...
Tue, 12 Jan 2021 13:07:23 GMT VeraLink Caching status...
Tue, 12 Jan 2021 13:07:24 GMT VeraLink Caching status...
Tue, 12 Jan 2021 13:07:25 GMT VeraLink Caching status...
Tue, 12 Jan 2021 13:07:26 GMT VeraLink Caching status...
Tue, 12 Jan 2021 13:07:27 GMT VeraLink Caching status...
Tue, 12 Jan 2021 13:07:28 GMT VeraLink Caching status...
Tue, 12 Jan 2021 13:07:29 GMT VeraLink Caching status...
Tue, 12 Jan 2021 13:07:30 GMT VeraLink Caching status...
Tue, 12 Jan 2021 13:07:31 GMT VeraLink Caching status...
2021-01-12T13:07:32.247Z ciao:Responder Sending (delayed 65ms) response via multicast on network interface docker0 (took 0 ms): [PTR] answers and [TXT,SRV,A,AAAA,NSEC,NSEC] additionals with size 342B
2021-01-12T13:07:32.279Z ciao:Responder Sending (delayed 96ms) response via multicast on network interface eth0 (took 1 ms): [PTR] answers and [TXT,SRV,A,AAAA,AAAA,NSEC,NSEC] additionals with size 370B
2021-01-12T13:07:32.287Z HAP-NodeJS:EventedHTTPServer [::ffff:192.168.3.237] New connection from client at interface eth0
2021-01-12T13:07:32.287Z HAP-NodeJS:EventedHTTPServer [::ffff:192.168.3.237] HTTP server listening on port 44439
2021-01-12T13:07:32.289Z HAP-NodeJS:EventedHTTPServer [::ffff:192.168.3.237] HTTP request: /accessories
2021-01-12T13:07:32.289Z HAP-NodeJS:HAPServer [0E:BB:BE:8A:11:8B] HAP Request: GET /accessories
2021-01-12T13:07:32.326Z HAP-NodeJS:EventedHTTPServer [::ffff:192.168.3.237] HTTP Response is finished
2021-01-12T13:07:32.330Z HAP-NodeJS:EventedHTTPServer [::ffff:192.168.3.237] HTTP connection was closed
2021-01-12T13:07:32.330Z HAP-NodeJS:EventedHTTPServer [::ffff:192.168.3.237] HTTP server was closed
2021-01-12T13:07:32.331Z HAP-NodeJS:EventedHTTPServer [::ffff:192.168.3.237] Client connection closed
us...

**Comment by miketartaglia** [comment]
I found this in the logs as well.  the only error I can find but it looks like it relates to Vera

Unhandled rejection Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: b5c23476-6db1-4e8c-963c-d60b421e1acc
    at Bridge.Accessory._this.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:419:15)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:436:25
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:423:21
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:10:18
    at /homebridge/node_modules/homebridge-vera/index.js:33:15
    at tryCatcher (/homebridge/node_modules/homebridge-vera/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/homebridge/node_modules/homebridge-vera/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/homebridge/node_modules/homebridge-vera/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/homebridge/node_modules/homebridge-vera/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/homebridge/node_modules/homebridge-vera/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/homebridge/node_modules/homebridge-vera/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/homebridge/node_modules/homebridge-vera/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/homebridge/node_modules/homebridge-vera/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/homebridge/node_modules/homebridge-vera/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:461:21)

**Comment by miketartaglia** [comment]
In addition, I do not get that error above when I take TRUE out of include sensor

**Comment by miketartaglia** [comment]
Did I give you the correct log information?

**Comment by drewcovi** [comment]
So that last bit is definitely a homebridge error specifically (https://github.com/homebridge/homebridge/issues/1685)... the logging im looking for is *much* earlier in the initialization and would be seen immediately on starting homebridge.

**Comment by miketartaglia** [comment]
I can try to attach the entire log (as an attachment)  if you want.  Please let me know.

**Comment by miketartaglia** [comment]
[homebridge.log-5.txt](https://github.com/damianxd/homebridge-vera/files/5810528/homebridge.log-5.txt)

**Comment by miketartaglia** [comment]
Unless I am misreading the homebridge.log-5.txt file I sent earlier, I can see the sensors being recognized, but I do not see any errors.

**Comment by miketartaglia** [comment]
is there anything further you need from me?

**Comment by miketartaglia** [comment]
It's been a few days.  I was wondering if you had a chance to look at the logs I sent in the last post?  If not, no big deal as I will try to find another solution for what I have.  Thank you for your time.

**Comment by drewcovi** [comment]
So far so good... seeing that sensors were added

``` log
Wed, 13 Jan 2021 18:36:33 GMT VeraLink Right Door Sensor ID:559
Wed, 13 Jan 2021 18:36:33 GMT VeraLink ------ Sensor Added: Right Door Sensor ID:559
```

**Comment by drewcovi** [comment]
@miketartaglia pretty sure you'll have success if you simply rename these sensors in vera since they're currently conflicting and causing that error we discussed earlier....

notice it happens right after one of your vera sensors with that name initializes. (the pet feeder also initializes in-between)

``` log
Wed, 13 Jan 2021 18:35:47 GMT VeraLink _Temperature Sensor ID:533
Wed, 13 Jan 2021 18:35:47 GMT VeraLink Humidity Dining Room ID:534
Wed, 13 Jan 2021 18:35:47 GMT VeraLink _Temperature Sensor ID:535
Wed, 13 Jan 2021 18:35:47 GMT VeraLink Humidity Bedroom ID:536
Wed, 13 Jan 2021 18:35:47 GMT VeraLink _Temperature Sensor ID:537
Wed, 13 Jan 2021 18:35:47 GMT VeraLink Humidity Living Room ID:538
Wed, 13 Jan 2021 18:35:47 GMT VeraLink _Temperature Sensor ID:539
Wed, 13 Jan 2021 18:35:47 GMT VeraLink Humidity Office ID:540
Wed, 13 Jan 2021 18:35:47 GMT VeraLink _Temperature Sensor ID:541
```

``` log
[1/13/2021, 1:36:33 PM] Initializing platform accessory '_Temperature Sensor'...
[1/13/2021, 1:36:33 PM] [PetSafeSmartFeed] Configuring 1 PetSafe Smart Feeder(s):
[1/13/2021, 1:36:33 PM] [PetSafeSmartFeed]  - Smart Feed - ID: 26676, Amount: Repeat Last Meal 
Unhandled rejection Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: b5c23476-6db1-4e8c-963c-d60b421e1acc
````

**Comment by miketartaglia** [comment]
I just wanted you to know, I recently had homekit thermostats installed to replace my Zwave ones.  After I removed the old ones from the Vera, all my sensors in vera came alive in homebridge.  As you mentioned previously it was the thermostats that had the duplicate naming issue.  Thank you for the guidance.
