### ISSUE TITLE
"Known Issues" section of Readme

### ISSUE THREAD

**Issue by tsfischer** [damianxd/homebridge-vera#188]
I think the "Known Issues" section of the readme might contain some out of date information.

- It mentions dimmers not working, but many of my devices are dimmers and they work fine.
- It mentions specifying a password... I don't think passwords are involved (maybe they are in some configurations?)
- Talks about the status not working properly. This seems to have been resolved.
- etc.

I'd fix it myself but I'm not sure what for sure is valid or not.

**Comment by drewcovi** [comment]
You are 100% correct 😉

**Comment by 5xPa** [comment]
Would be grateful for any info you have on installing this plugin. I installed via Hoobs. If you have  terminal command  for installation I could try. I did try terminal command on Hoobs site but on loading it sits at
3/9/2021, 9:59:08 AM at Immediate.Async.drainQueues [as _onImmediate] (/home/hoobs/.hoobs/node_modules/bluebird/js/release/async.js:15:14)
3/9/2021, 9:59:08 AM at processImmediate (internal/timers.js:461:21)
