### ISSUE TITLE
Cannot set standalone to false for bridged

### ISSUE THREAD

**Issue by CelticWebSolutions** [damianxd/homebridge-vera#22]
after spending a long time working out how to get this to run as a standalone, I finally found that if I allow the settings to be true for bridged it will work.  If I set bridged to false, the server will not start.

The error is as follows

Command-line input received:
	VeraIP: 192.168.1.95
	happort: 6200
	bridged: false
	ignorerooms: 11
Configuration saved!
HAP-NodeJS starting...
/usr/local/lib/node_modules/homebridge-vera/node_modules/hap-nodejs/lib/model/AccessoryInfo.js:53
  return util.format("AccessoryInfo.%s.json", username.replace(/:/g,"").toUpperCase());
                                                      ^

TypeError: Cannot read property 'replace' of undefined
    at Function.AccessoryInfo.persistKey (/usr/local/lib/node_modules/homebridge-vera/node_modules/hap-nodejs/lib/model/AccessoryInfo.js:53:55)
    at Function.AccessoryInfo.load (/usr/local/lib/node_modules/homebridge-vera/node_modules/hap-nodejs/lib/model/AccessoryInfo.js:70:27)
    at Accessory.publish (/usr/local/lib/node_modules/homebridge-vera/node_modules/hap-nodejs/lib/Accessory.js:290:39)
    at /usr/local/lib/node_modules/homebridge-vera/lib/functions.js:52:27
    at Array.forEach (native)
    at Object.module.processall (/usr/local/lib/node_modules/homebridge-vera/lib/functions.js:40:25)
    at /usr/local/lib/node_modules/homebridge-vera/VeraLink.js:207:27
    at /usr/local/lib/node_modules/homebridge-vera/node_modules/async/lib/async.js:718:13
    at iterate (/usr/local/lib/node_modules/homebridge-vera/node_modules/async/lib/async.js:262:13)
    at /usr/local/lib/node_modules/homebridge-vera/node_modules/async/lib/async.js:274:29

**Comment by damianxd** [comment]
Fixed on the latest version
