### ISSUE TITLE
Error install thru Synology Docker

### ISSUE THREAD

**Issue by moccajava33** [damianxd/homebridge-vera#29]
Hi,

I have Hombridge setup ok in my Synology Docker.

Issue faced when trying to setup homebridge-vera (btw NPM search shows two different versions).
Appears that Synology command line does not have apt-get so I cannot install Git.
I'm not that great in Linux commands so a bit in-depth guide will help.

xxx@Diskstation:/$ sudo npm install -g homebridge-vera
Password: 
npm WARN addRemoteGit Error: not found: git
npm WARN addRemoteGit     at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:78:19)
npm WARN addRemoteGit     at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:82:29)
npm WARN addRemoteGit     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:93:16
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:82:15)
npm WARN addRemoteGit  git://github.com/KhaosT/ed25519.git resetting remote /root/.npm/_git-remotes/git-github-com-KhaosT-ed25519-git-d8bdee1d because of error: { [Error: not found: git] code: 'ENOGIT' }
npm WARN addRemoteGit Error: not found: git
npm WARN addRemoteGit     at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:78:19)
npm WARN addRemoteGit     at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:82:29)
npm WARN addRemoteGit     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:93:16
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:82:15)
npm WARN addRemoteGit  git://github.com/KhaosT/node-curve25519.git resetting remote /root/.npm/_git-remotes/git-github-com-KhaosT-node-curve25519-git-750fb09d because of error: { [Error: not found: git] code: 'ENOGIT' }
npm WARN addRemoteGit Error: not found: git
npm WARN addRemoteGit     at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:78:19)
npm WARN addRemoteGit     at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:82:29)
npm WARN addRemoteGit     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:93:16
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:82:15)
npm WARN addRemoteGit  git://github.com/KhaosT/node-srp.git resetting remote /root/.npm/_git-remotes/git-github-com-KhaosT-node-srp-git-b14235ae because of error: { [Error: not found: git] code: 'ENOGIT' }
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/KhaosT/ed25519.git /root/.npm/_git-remotes/git-github-com-KhaosT-ed25519-git-d8bdee1d: undefined
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/KhaosT/ed25519.git /root/.npm/_git-remotes/git-github-com-KhaosT-ed25519-git-d8bdee1d: undefined
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/KhaosT/node-curve25519.git /root/.npm/_git-remotes/git-github-com-KhaosT-node-curve25519-git-750fb09d: undefined
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/KhaosT/node-curve25519.git /root/.npm/_git-remotes/git-github-com-KhaosT-node-curve25519-git-750fb09d: undefined
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/KhaosT/node-srp.git /root/.npm/_git-remotes/git-github-com-KhaosT-node-srp-git-b14235ae: undefined
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror git://github.com/KhaosT/node-srp.git /root/.npm/_git-remotes/git-github-com-KhaosT-node-srp-git-b14235ae: undefined
 
> spawn-sync@1.0.15 postinstall /usr/local/lib/node_modules/homebridge-vera/node_modules/sync-request/node_modules/spawn-sync
> node postinstall

npm ERR! Linux 3.10.77
npm ERR! argv "/volume1/@appstore/Node.js_v4/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "homebridge-vera"
npm ERR! node v4.2.6
npm ERR! npm  v2.14.12
npm ERR! code ENOGIT

npm ERR! not found: git
npm ERR! 
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! Please include the following file with any support request:
npm ERR!     /npm-debug.log

**Comment by moccajava33** [comment]
Solved issue. I installed Git installed of Git Server on Synology.
