### ISSUE TITLE
Crash when scrolling on iPhone app Server hangs

### ISSUE THREAD

**Issue by DrJeff** [damianxd/homebridge-vera#4]
So the server hangs when the client is scrolling and gives this: 
``` 
Homebridge is running on port 51826.
/usr/local/lib/node_modules/homebridge-veralink/node_modules/sync-request/index.js:31
    throw new Error(response.error.message || response.error || response);
    ^

Error: socket hang up
    at Object.doRequest [as request] (/usr/local/lib/node_modules/homebridge-veralink/node_modules/sync-request/index.js:31:11)
    at Object.Switch.getStatus (/usr/local/lib/node_modules/homebridge-veralink/lib/types/switch.js:43:31)
    at null.<anonymous> (/usr/local/lib/node_modules/homebridge-veralink/lib/types/switch.js:99:38)
    at emitTwo (events.js:87:13)
    at emit (events.js:172:7)
    at Characteristic.getValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:120:10)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:438:20)
    at Array.forEach (native)
    at Bridge.Accessory._handleGetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:410:8)
    at emitThree (events.js:97:13)
```
I think it can not get the status for all the devices then barfs??
How do I fix and what else do you need from me?

**Comment by damianxd** [comment]
That error seems to be from a connection problem between your device and vera. Can you do a continuous ping to vera IP?
Like:
ping <ip to vera> -c 9999999
and check for any loose packet

**Comment by DrJeff** [comment]
@damianxd ok I couldn't wait for all 9999999 packets to finish but I see no loss look below. 
```
--- 192.168.0.228 ping statistics ---
172 packets transmitted, 172 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 0.289/0.411/0.509/0.035 ms
```

**Comment by DrJeff** [comment]
Ok I let it run longer still no packet loss!
```
--- 192.168.0.228 ping statistics ---
4591 packets transmitted, 4591 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 0.272/0.409/10.197/0.149 ms
```

**Comment by damianxd** [comment]
are you still getting the same error?

**Comment by DrJeff** [comment]
Yes same error and crash but the ping shows no difference or packet loss. I believe it is with the iPhone side. ~~On the Insteon app no crash (it doesn't try to poll a bunch of devices only 1 at a time).~~ But with the Eve app and Home app when it is polling on the UI scroll the server crashes, also the Insteon app when all devices are shown. Any way to manipulate the code to not hang up? It looks to only show about 60+ of my devices I have alot more 100+, could that be an issue?

**Comment by DrJeff** [comment]
Ok got a question if you are using sync-request for request can just using request work any better and where would I drop those in to try?

**Comment by DrJeff** [comment]
@damianxd 
Ok I broke the devices into smaller numbers of device and now it works. I think I just had to many devices to import at once. I get the same problem with VeraHomeKit, the devices all load at once and I get a reached limit message on the iPhone, the server just hangs.
