### ISSUE TITLE
0.5.3 fails undefined is not a function while processing devices

### ISSUE THREAD

**Issue by acidprime** [damianxd/homebridge-vera#57]
```js
*** WARNING *** Please fix your application to use the native API of Avahi!
stdout
06:06:37
*** WARNING *** For more information see &lt;http://0pointer.de/avahi-compat?s=libdns_sd&amp;e=nodejs&amp;f=DNSServiceRegister&gt;
stdout
06:06:38
[12/11/2016, 6:06:38 AM] Loaded plugin: homebridge-vera
stdout
06:06:38
VeraLink initializing
stdout
06:06:38
[12/11/2016, 6:06:38 AM] Registering platform 'homebridge-veralink.Vera'
stdout
06:06:38
[12/11/2016, 6:06:38 AM] ---
stdout
06:06:38
[12/11/2016, 6:06:38 AM] Loaded config.json with 0 accessories and 1 platforms.
stdout
06:06:38
[12/11/2016, 6:06:38 AM] ---
stdout
06:06:39
[12/11/2016, 6:06:39 AM] Loading 1 platforms...
stdout
06:06:39
[12/11/2016, 6:06:39 AM] [36m[Vera][39m Initializing Vera platform...
stdout
06:06:39
  [36;1mVeraLink [0mUsing url: http://192.168.53.80:3480/data_request?id=lu_sdata [36m+0ms[0m
stdout
06:06:39
  [36;1mVeraLink [0m------ Lock Added: Back Door Lock ID:38 [36m+7ms[0m
stdout
06:06:39
  [36;1mVeraLink [0m------ Lightbulb Added: Bathroom Sink ID:190 [36m+17ms[0m
stdout
06:06:39
[31mUnhandled rejection TypeError: undefined is not a function
stdout
06:06:39
    at /usr/lib/node_modules/homebridge-vera/lib/functions.js:159:55
stdout
06:06:39
    at Array.forEach (native)
stdout
06:06:39
    at Object.module.processdevices (/usr/lib/node_modules/homebridge-vera/lib/functions.js:153:14)
stdout
06:06:39
    at Object.module.processall (/usr/lib/node_modules/homebridge-vera/lib/functions.js:41:30)
stdout
06:06:39
    at /usr/lib/node_modules/homebridge-vera/index.js:57:42
stdout
06:06:39
    at tryCatcher (/usr/lib/node_modules/homebridge-vera/node_modules/request-promise/node_modules/bluebird/js/release/util.js:16:23)
stdout
06:06:39
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/homebridge-vera/node_modules/request-promise/node_modules/bluebird/js/release/promise.js:510:31)
stdout
06:06:39
    at Promise._settlePromise (/usr/lib/node_modules/homebridge-vera/node_modules/request-promise/node_modules/bluebird/js/release/promise.js:567:18)
stdout
06:06:39
    at Promise._settlePromise0 (/usr/lib/node_modules/homebridge-vera/node_modules/request-promise/node_modules/bluebird/js/release/promise.js:612:10)
stdout
06:06:39
    at Promise._settlePromises (/usr/lib/node_modules/homebridge-vera/node_modules/request-promise/node_modules/bluebird/js/release/promise.js:691:18)
stdout
06:06:39
    at Async._drainQueue (/usr/lib/node_modules/homebridge-vera/node_modules/request-promise/node_modules/bluebird/js/release/async.js:138:16)
stdout
06:06:39
    at Async._drainQueues (/usr/lib/node_modules/homebridge-vera/node_modules/request-promise/node_modules/bluebird/js/release/async.js:148:10)
stdout
06:06:39
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/lib/node_modules/homebridge-vera/node_modules/request-promise/node_modules/bluebird/js/release/async.js:17:14)
stdout
06:06:39
    at processImmediate [as _immediateCallback] (timers.js:367:17)[0m

```

**Comment by acidprime** [comment]
Vera firmware `1.7.2139`

**Comment by acidprime** [comment]
I tried version `0.0.9` of the npm and it "works" with the same docker container, but randomly crashes which is why I was trying to get the latest version working.

**Comment by acidprime** [comment]
<img width="820" alt="screen shot 2016-12-11 at 12 44 30 am" src="https://cloud.githubusercontent.com/assets/1173142/21079086/0b6113a2-bf3b-11e6-82be-4fecd289a2da.png">

I don't have any fans and so I commented the offending line conditional and it loaded. Given the commit history includes recent churn on the fan support I am guessing there is a lack of error catching in its new code base that conflicts with my environment.

**Comment by drewcovi** [comment]
What version of Node are you running this on? Have you tried updating? I have fans and more. No issues with the latest release.

**Comment by drewcovi** [comment]
Also @damianxd it looks like an update to NPM would help as master is a bit beyond his screenshot...

**Comment by Laver** [comment]
Sounds like a dimmable light exists without a name. It should just need better null checks for the fan "detection".

**Comment by drewcovi** [comment]
you can set a device to not have a name? i thought vera required that.

**Comment by Laver** [comment]
Can't hurt to have a better null check.

**Comment by damianxd** [comment]
I'm unable to offer any kind of support right now... I've too much work with a project :/
I will resume on this on January unless it starts failing for me too

**Comment by funstuff234** [comment]
Same exact error here on latest version.

**Comment by funstuff234** [comment]
I cloned in the latest code and installed from that, it still didn't work. I then commented out the fan code like acid prime did in the earlier version and that worked; it looks like the null checks that were implemented were not a solution. For reference, I don't have any devices without a name, so not sure whats causing it.

**Comment by drewcovi** [comment]
Closing as per comments by @cmonteiro128 that all seems resolved with the latest null check. @acidprime please comment here if we need to re-open.
