### ISSUE TITLE
Problem with running at bootup (systemd)

### ISSUE THREAD

**Issue by knaackville** [damianxd/homebridge-vera#78]
Hello,

Everything seems to run during normal usage, but when attempting to run homebridge on a raspberry pi per the instructions here (https://timleland.com/setup-homebridge-to-start-on-bootup/), I get the following error in the journal and it fails to run:

Jan 15 19:38:43 raspberrypi homebridge[3254]: [1/15/2017, 7:38:43 PM] [Vera] Initializing Vera platform...
Jan 15 19:38:43 raspberrypi homebridge[3254]: /usr/local/lib/node_modules/homebridge-vera/index.js:97
Jan 15 19:38:43 raspberrypi homebridge[3254]: if ( e.code != 'EEXIST' ) throw e;
Jan 15 19:38:43 raspberrypi homebridge[3254]: ^
Jan 15 19:38:43 raspberrypi homebridge[3254]: Error: ENOENT: no such file or directory, mkdir '/home/homebridge/.veralink'
Jan 15 19:38:43 raspberrypi homebridge[3254]: at Error (native)
Jan 15 19:38:43 raspberrypi homebridge[3254]: at Object.fs.mkdirSync (fs.js:922:18)
Jan 15 19:38:43 raspberrypi homebridge[3254]: at loadconfig (/usr/local/lib/node_modules/homebridge-vera/index.js:94:16)
Jan 15 19:38:43 raspberrypi homebridge[3254]: at Object.VeraLinkPlatform (/usr/local/lib/node_modules/homebridge-vera/index.js:23:23)
Jan 15 19:38:43 raspberrypi homebridge[3254]: at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:291:32)
Jan 15 19:38:43 raspberrypi homebridge[3254]: at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:77:36)
Jan 15 19:38:43 raspberrypi homebridge[3254]: at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
Jan 15 19:38:43 raspberrypi homebridge[3254]: at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
Jan 15 19:38:43 raspberrypi homebridge[3254]: at Module._compile (module.js:570:32)
Jan 15 19:38:43 raspberrypi homebridge[3254]: at Object.Module._extensions..js (module.js:579:10)
Jan 15 19:38:43 raspberrypi homebridge[3254]: at Module.load (module.js:487:32)
Jan 15 19:38:43 raspberrypi homebridge[3254]: at tryModuleLoad (module.js:446:12)
Jan 15 19:38:43 raspberrypi homebridge[3254]: at Function.Module._load (module.js:438:3)
Jan 15 19:38:43 raspberrypi homebridge[3254]: at Module.runMain (module.js:604:10)
Jan 15 19:38:43 raspberrypi homebridge[3254]: at run (bootstrap_node.js:394:7)
Jan 15 19:38:43 raspberrypi homebridge[3254]: at startup (bootstrap_node.js:149:9)
Jan 15 19:38:43 raspberrypi homebridge[3254]: at bootstrap_node.js:509:3
Jan 15 19:38:43 raspberrypi systemd[1]: homebridge.service: main process exited, code=exited, status=1/FAILURE
Jan 15 19:38:43 raspberrypi systemd[1]: Unit homebridge.service entered failed state.

It appears to go away when removing the homebridge-vera plugin from the config.json file, and runs successfully otherwise with other plugins.  Thoughts?

**Comment by knaackville** [comment]
Never mind... I just used PM2 and this worked well and avoided having two config files and things.  Thanks anyway!
