### ISSUE TITLE
Thermostat fails to update due to type exception while retrieving Battery Level

### ISSUE THREAD

**Issue by bblacey** [damianxd/homebridge-vera#84]
Thermostat - GoControl GC-TBZ48 (Battery powered z-wave Thermostat)
Vera Plus, firmware 1.7.2414 (UI7)

```
Accessory [Homebridge] Getting value for Characteristic "Temperature Display Units" +1ms
  VeraLink Temperature display unit for Thermostat Living RM is 1 +2ms
  Accessory [Homebridge] Got Characteristic "Temperature Display Units" value: 1 +1ms
  Accessory [Homebridge] Getting value for Characteristic "Target Temperature" +0ms
  VeraLink Getting target temp value for Thermostat Living RM +1ms
  VeraLink Making setpoint request for device Thermostat Living RM +1ms
  VeraLink [Before Conversion] Current Temperature for Thermostat #Thermostat Living RM is 65 +0ms
  VeraLink Current Temperature for Thermostat #Thermostat Living RM is 18.333333333333332 +0ms
  Accessory [Homebridge] Got Characteristic "Target Temperature" value: 18.333333333333332 +2ms
  Accessory [Homebridge] Getting value for Characteristic "Current Temperature" +0ms
  VeraLink Getting current temp. value for Thermostat Living RM +2ms
  VeraLink Making temperature request for device Thermostat Living RM +0ms
  VeraLink [Before Conversion] Current Temperature for Thermostat #Thermostat Living RM is 65 +0ms
  VeraLink Current Temperature for Thermostat #Thermostat Living RM is 18.333333333333332 +1ms
  Accessory [Homebridge] Got Characteristic "Current Temperature" value: 18.333333333333332 +2ms
  Accessory [Homebridge] Getting value for Characteristic "Target Heating Cooling State" +0ms
  VeraLink Getting target heating/cooling value for Thermostat Living RM +1ms
  Accessory [Homebridge] Got Characteristic "Target Heating Cooling State" value: 1 +1ms
  Accessory [Homebridge] Getting value for Characteristic "Current Heating Cooling State" +1ms
  VeraLink Getting current heating/cooling state for Thermostat Living RM +1ms
  VeraLink Making hvacstate request for device Thermostat Living RM +0ms
  VeraLink HVAC State returned as:  PendingHeat +1ms
  Accessory [Homebridge] Got Characteristic "Current Heating Cooling State" value: 0 +1ms
  Accessory [Homebridge] Getting value for Characteristic "Status Low Battery" +0ms
  VeraLink TypeError: Cannot read property 'BatteryLevel' of undefined
  VeraLink     at Object.module.getVariable (/usr/local/lib/node_modules/homebridge-vera/lib/functions.js:24:22)
  VeraLink     at Object.Thermostat.getBatteryLevel (/usr/local/lib/node_modules/homebridge-vera/lib/types/thermostat.js:241:34)
  VeraLink     at null.<anonymous> (/usr/local/lib/node_modules/homebridge-vera/lib/types/thermostat.js:337:28)
  VeraLink     at emitThree (events.js:97:13)
  VeraLink     at emit (events.js:175:7)
  VeraLink     at Characteristic.getValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:120:10)
  VeraLink     at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:634:20)
  VeraLink     at Array.forEach (native)
  VeraLink     at Bridge.Accessory._handleGetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:598:8)
  VeraLink     at emitMany (events.js:108:13)
  VeraLink     at HAPServer.emit (events.js:182:7)
  VeraLink     at HAPServer._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:926:10)
  VeraLink     at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
  VeraLink     at emitNone (events.js:67:13)
  VeraLink     at IncomingMessage.emit (events.js:166:7)
  VeraLink     at endReadableNT (_stream_readable.js:905:12)
  VeraLink     at nextTickCallbackWith2Args (node.js:441:9)
  VeraLink     at process._tickCallback (node.js:355:17) +1ms
  VeraLink Caching status... +2s
  VeraLink Caching status... +3s
```

**Comment by bblacey** [comment]
For additional info, here is the output from curl that shows the battery level for the thermostat.

```
curl 'http://192.168.1.210:3480/data_request?id=variableget&DeviceNum=58&serviceId=urn:micasaverde-coerviceId:HaDevice1&Variable=BatteryLevel'
100
```

**Comment by bblacey** [comment]
I'm not familiar with the code base but it looks like https://github.com/damianxd/homebridge-vera/blob/master/lib/types/thermostat.js#L241 using a different getVariable() method signature than what is defined https://github.com/damianxd/homebridge-vera/blob/master/lib/functions.js#L16
