### ISSUE TITLE
Not loading after update

### ISSUE THREAD

**Issue by reallybman** [damianxd/homebridge-vera#97]
Hi All - now getting this error after upgrading to the latest release:

Unhandled rejection Error: Accessories must be created with a valid UUID.
    at new Accessory (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:47:20)
    at Object.module.newDevice (/usr/lib/node_modules/homebridge-vera/lib/types/lock.js:58:25)
    at /usr/lib/node_modules/homebridge-vera/lib/functions.js:234:49
    at Array.forEach (native)
    at Object.module.processdevices (/usr/lib/node_modules/homebridge-vera/lib/functions.js:175:16)
    at Object.module.processall (/usr/lib/node_modules/homebridge-vera/lib/functions.js:63:32)
    at /usr/lib/node_modules/homebridge-vera/index.js:57:42
    at tryCatcher (/usr/lib/node_modules/homebridge-vera/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/homebridge-vera/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/usr/lib/node_modules/homebridge-vera/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/usr/lib/node_modules/homebridge-vera/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/usr/lib/node_modules/homebridge-vera/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/usr/lib/node_modules/homebridge-vera/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/usr/lib/node_modules/homebridge-vera/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/usr/lib/node_modules/homebridge-vera/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)

**Comment by drewcovi** [comment]
How recently did you pull the latest? This was fixed about a week back.

**Comment by reallybman** [comment]
Just pulled it tonight using the git url. I had to do a clean install because I fudged something up. Earlier today I used the NPM package install an that loaded but was unstable. So, tried the url to see if that would clear up the stability issues - but can't get it to load...

**Comment by drewcovi** [comment]
Yeah. @damianxd added me as a contributor here but I can't yet update NPM. Will keep you posted. But for now rely on the git url

**Comment by damianxd** [comment]
I will update NPM tomorrow morning

**Comment by reallybman** [comment]
Will that correct my issue?

**Comment by reallybman** [comment]
This morning I tried downgrading node from 7.5 to 6.9.5, still didn't work.

**Comment by reallybman** [comment]
Found this to be a different plugin causing the issue.

**Comment by akhoury** [comment]
@reallybman would u mind sharing which plugin did that?

**Comment by reallybman** [comment]
Yes - harmonyhub
