### ISSUE TITLE
Unhandled rejection RequestError: Error: connect ECONNREFUSED

### ISSUE THREAD

**Issue by HA-Enthusiast** [damianxd/homebridge-vera#98]
Hi All! I'm having some difficulty getting this plugin to work. I used to run this on my Mac with no problem, but since I've switched to a RPi 3, no bueno. 

Unhandled rejection RequestError: Error: connect ECONNREFUSED 192.168.1.25:3480
    at new RequestError (/usr/lib/node_modules/homebridge-vera/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/usr/lib/node_modules/homebridge-vera/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/usr/lib/node_modules/homebridge-vera/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/usr/lib/node_modules/homebridge-vera/node_modules/request/request.js:186:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/usr/lib/node_modules/homebridge-vera/node_modules/request/request.js:845:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1278:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

Unhandled rejection RequestError: Error: connect ECONNREFUSED 192.168.1.25:3480
    at new RequestError (/usr/lib/node_modules/homebridge-vera/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/usr/lib/node_modules/homebridge-vera/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/usr/lib/node_modules/homebridge-vera/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/usr/lib/node_modules/homebridge-vera/node_modules/request/request.js:186:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/usr/lib/node_modules/homebridge-vera/node_modules/request/request.js:845:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1278:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

Unhandled rejection RequestError: Error: connect ECONNREFUSED 192.168.1.25:3480
    at new RequestError (/usr/lib/node_modules/homebridge-vera/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/usr/lib/node_modules/homebridge-vera/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/usr/lib/node_modules/homebridge-vera/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/usr/lib/node_modules/homebridge-vera/node_modules/request/request.js:186:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/usr/lib/node_modules/homebridge-vera/node_modules/request/request.js:845:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1278:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

Unhandled rejection RequestError: Error: connect ECONNREFUSED 192.168.1.25:3480
    at new RequestError (/usr/lib/node_modules/homebridge-vera/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/usr/lib/node_modules/homebridge-vera/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/usr/lib/node_modules/homebridge-vera/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/usr/lib/node_modules/homebridge-vera/node_modules/request/request.js:186:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/usr/lib/node_modules/homebridge-vera/node_modules/request/request.js:845:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1278:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

Unhandled rejection RequestError: Error: connect ECONNREFUSED 192.168.1.25:3480
    at new RequestError (/usr/lib/node_modules/homebridge-vera/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/usr/lib/node_modules/homebridge-vera/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/usr/lib/node_modules/homebridge-vera/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/usr/lib/node_modules/homebridge-vera/node_modules/request/request.js:186:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/usr/lib/node_modules/homebridge-vera/node_modules/request/request.js:845:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1278:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

Unhandled rejection RequestError: Error: connect ECONNREFUSED 192.168.1.25:3480
    at new RequestError (/usr/lib/node_modules/homebridge-vera/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/usr/lib/node_modules/homebridge-vera/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/usr/lib/node_modules/homebridge-vera/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/usr/lib/node_modules/homebridge-vera/node_modules/request/request.js:186:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/usr/lib/node_modules/homebridge-vera/node_modules/request/request.js:845:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1278:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

Unhandled rejection RequestError: Error: connect ECONNREFUSED 192.168.1.25:3480
    at new RequestError (/usr/lib/node_modules/homebridge-vera/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/usr/lib/node_modules/homebridge-vera/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/usr/lib/node_modules/homebridge-vera/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/usr/lib/node_modules/homebridge-vera/node_modules/request/request.js:186:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/usr/lib/node_modules/homebridge-vera/node_modules/request/request.js:845:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1278:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

Unhandled rejection RequestError: Error: connect ECONNREFUSED 192.168.1.25:3480
    at new RequestError (/usr/lib/node_modules/homebridge-vera/node_modules/request-promise-core/lib/errors.js:14:15)
    at Request.plumbing.callback (/usr/lib/node_modules/homebridge-vera/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/usr/lib/node_modules/homebridge-vera/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/usr/lib/node_modules/homebridge-vera/node_modules/request/request.js:186:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/usr/lib/node_modules/homebridge-vera/node_modules/request/request.js:845:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1278:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by djrobx** [comment]
Looks like whatever is at 192.168.1.25 is rejecting the request on port 3480.   

Verify that 192.168.1.25 is the correct Vera IP.    You can also test telnetting to the IP.   If it's working you should see something like below:

**telnet 192.168.0.9 3480**

Trying 192.168.0.9...
Connected to 192.168.0.9.
Escape character is '^]'.
foo

HTTP/1.1 400 Bad Request
Content-Type: text/plain
Content-Length: 54
Connection: close

Error 400: Bad Request
Can not parse request: [foo
]Connection closed by foreign host.

**Comment by drewcovi** [comment]
Yeah as @djrobx mentioned, and ensure you have an IP reservation on your router for your Vera

**Comment by HA-Enthusiast** [comment]
Okay. I'm positive that's the IP address of my Vera. I can even type it in the url field and it will ask for my login.

Problem is, the port number is coming out of nowhere. I tried adding the port number that keeps popping up (3480) and I tried it without. Same problem. 

As for the telnetting, I'm not sure what you're asking me to do. Can you help explain? I'm a total noob to this stuff...

**Comment by drewcovi** [comment]
@HA-Enthusiast are you still having this issue? It doesn't seem related to this plugin, as you've already noted it's working on your Mac.

**Comment by mehmetoztemel** [comment]
I am having the same issue and I am positive that my Vera IP is correct.

**Comment by drewcovi** [comment]
@machinen @ha-enthusiast are you running as a homebridge plugin? Or in standalone? If standalone, it hasn't gotten much attention lately. I'd recommend the conventional homebridgr plugin approach.

**Comment by djrobx** [comment]
If I recall there's a "secure my Vera" setting that blocks LAN access to the API. You'll want to turn that off. Your security is fine as long as your LAN is secure.

**Comment by austrasien** [comment]
Hello, I'm having the same problem. How to turn off "secure my vera" to unblock LAN access to the API?
